ALTER TYPE "QuestionType" ADD VALUE 'FILL_GAP';
ALTER TYPE "QuestionType" ADD VALUE 'MATCH_PAIRS';
ALTER TYPE "QuestionType" ADD VALUE 'SORT_ORDER';
ALTER TYPE "QuestionType" ADD VALUE 'DRAG_DROP';
ALTER TYPE "QuestionType" ADD VALUE 'FIND_MISTAKE';
ALTER TYPE "QuestionType" ADD VALUE 'CODE_COMPLETION';
ALTER TYPE "QuestionType" ADD VALUE 'DEBUG_CODE';
ALTER TYPE "QuestionType" ADD VALUE 'CONNECT_CONCEPT';
ALTER TYPE "QuestionType" ADD VALUE 'LISTEN_ANSWER';
ALTER TYPE "QuestionType" ADD VALUE 'INTERACTIVE_IMAGE';
ALTER TYPE "QuestionType" ADD VALUE 'MEMORY_CARDS';
ALTER TYPE "QuestionType" ADD VALUE 'SPEAK';
ALTER TYPE "QuestionType" ADD VALUE 'DRAW';
ALTER TYPE "QuestionType" ADD VALUE 'GEOMETRY';
ALTER TABLE "Question" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "config" JSONB, ADD COLUMN "grading" JSONB;
ALTER TABLE "Attempt" ADD COLUMN "questionsSnapshot" JSONB, ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "AttemptAnswer" ADD COLUMN "payload" JSONB;
ALTER TABLE "Lesson" ADD COLUMN "prerequisiteId" UUID, ADD COLUMN "unlockScore" INTEGER NOT NULL DEFAULT 70;
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_prerequisiteId_fkey" FOREIGN KEY ("prerequisiteId") REFERENCES "Lesson"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
UPDATE "Attempt" a SET "questionsSnapshot" = (SELECT jsonb_agg(to_jsonb(q) || jsonb_build_object('options', COALESCE((SELECT jsonb_agg(to_jsonb(o) ORDER BY o.position) FROM "QuestionOption" o WHERE o."questionId"=q.id), '[]'::jsonb)) ORDER BY array_position(a."questionIds", q.id::text)) FROM "Question" q WHERE q.id::text = ANY(a."questionIds"));
