import { lesson, mc, tf, txt, num, type GradeCurriculum } from './types';

export const english: GradeCurriculum = {
  5: [
    lesson(
      'Subject pronouns: I, you, he, she',
      'Ingliz tiliga ilk qadam',
      'Gapning egasini mos kishilik olmoshi bilan almashtiring.',
      'Subject pronouns gapda kim yoki nima ish bajarishini ko‘rsatadi. I — men, you — sen yoki siz, he — u (erkak), she — u (ayol), it — narsa yoki hayvon uchun u, we — biz, they — ular.\n\nAli is a pupil. He is a pupil. Bu yerda He Ali nomini takrorlamaslik uchun ishlatilgan. Madina bilan she, ikki yoki undan ortiq odam bilan they ishlatiladi. I ingliz tilida har doim bosh harf bilan yoziladi.\n\nOlmoshni faqat oxirgi so‘zga qarab tanlamang. Gap kim haqida ekanini aniqlang. My sister — she, my brother — he, my friends — they. Siz va do‘stingiz birga bo‘lsangiz, we deb aytasiz.',
      'Madina and I are pupils. → We are pupils.\nMy books are new. → They are new.\nMy school is big. → It is big.',
      [
        mc(
          'Ali is a boy. ___ is a pupil.',
          ['He', 'She', 'They', 'We'],
          'He',
          'Ali haqida he ishlatiladi.',
        ),
        tf('We olmoshi “biz” degani.', true, 'We gapiruvchi va yana boshqa odamlarni bildiradi.'),
        txt('“Ular” olmoshini inglizcha yozing.', 'they', 'They — ular.'),
        mc(
          'My sister is kind. ___ is kind.',
          ['She', 'He', 'It', 'We'],
          'She',
          'Sister — opa yoki singil, she ishlatiladi.',
        ),
        txt(
          'Madina and I are friends. Egani bitta olmosh bilan yozing.',
          'we',
          'Gapiruvchi ham guruhga kirgani uchun we.',
        ),
        mc(
          'My books are on the desk. ___ are on the desk.',
          ['They', 'It', 'He', 'I'],
          'They',
          'Books ko‘plik, shuning uchun they.',
        ),
      ],
    ),
    lesson(
      'To be: am, is, are',
      'Oddiy gaplar',
      'Ega bilan am, is yoki are ni to‘g‘ri ishlating.',
      'To be fe’li odam yoki narsaning kimligini, qandayligini va qayerdaligini ifodalaydi. I bilan am; he, she, it bilan is; you, we, they bilan are ishlatiladi. I am a pupil. She is happy. They are at school.\n\nInkor uchun be dan keyin not qo‘shamiz: I am not late. He is not tired. We are not at home. Is not qisqa shaklda isn’t, are not aren’t bo‘ladi.\n\nSavolda am, is yoki are egadan oldinga chiqadi. You are ready. → Are you ready? Qisqa javob: Yes, I am. yoki No, I am not. Am, is, are oddiy hozirgi zamondagi be shakllaridir.',
      'She is a teacher. → Is she a teacher?\nThey are in the library. → They are not in the library.\nI am happy. → I’m happy.',
      [
        txt('I ___ a pupil. Bo‘sh joyni to‘ldiring.', 'am', 'I bilan am ishlatiladi.'),
        mc('She ___ happy.', ['is', 'am', 'are', 'be'], 'is', 'She bilan is.'),
        tf('They is at school — to‘g‘ri gap.', false, 'They bilan are: They are at school.'),
        txt('You ___ my friend.', 'are', 'You bilan are.'),
        mc(
          'You are ready. Gapning savol shakli qaysi?',
          ['Are you ready?', 'Is you ready?', 'You ready are?', 'Am you ready?'],
          'Are you ready?',
          'Are egadan oldinga chiqadi.',
        ),
        txt(
          'We are not late. “are not” ning qisqa shaklini yozing.',
          "aren't|aren’t",
          'Are not qisqa shaklda aren’t bo‘ladi.',
        ),
      ],
    ),
    lesson(
      'Possessive adjectives: my, your, their',
      'Oila va buyumlar',
      'Buyum kimga tegishli ekanini egalik sifatlari bilan ayting.',
      'My — mening, your — sening yoki sizning, his — uning (erkak), her — uning (ayol), its — uning (narsa), our — bizning, their — ularning. Bu so‘zlar odatda otdan oldin keladi: my book, her bag, our classroom.\n\nHe va his turli vazifada ishlatiladi. He is my friend. His name is Ali. He gapning egasi, his esa name kimga tegishli ekanini bildiradi.\n\nBitta buyum ko‘p odamga tegishli bo‘lishi mumkin: their classroom. Egalik so‘zini buyumning ko‘plik yoki birlik shakliga qarab emas, egasiga qarab tanlang. Madina’s pen → her pen; Ali and Sardor’s room → their room.',
      'I have a book. This is my book.\nWe have a classroom. This is our classroom.\nShe has a pencil. This is her pencil.',
      [
        mc(
          'I have a book. It is ___ book.',
          ['my', 'his', 'their', 'our'],
          'my',
          'I uchun egalik sifati my.',
        ),
        tf('Our so‘zi “bizning” degani.', true, 'Our guruhimizga tegishli ekanini bildiradi.'),
        txt(
          '“Ularning sumkasi” iborasidagi egalik sifatini inglizcha yozing.',
          'their',
          'Their bag — ularning sumkasi.',
        ),
        mc(
          'Madina has a pen. It is ___ pen.',
          ['her', 'his', 'my', 'its'],
          'her',
          'Madina uchun her ishlatiladi.',
        ),
        txt('We study in a classroom. It is ___ classroom.', 'our', 'We uchun egalik sifati our.'),
        mc(
          'Ali and Sardor have a room. It is ___ room.',
          ['their', 'his', 'her', 'your'],
          'their',
          'Ikki egasi bor, ular uchun their.',
        ),
      ],
    ),
    lesson(
      'Have got va has got',
      'Nimalarga egamiz?',
      'Have got bilan egalikni bildiring va oddiy savol tuzing.',
      'Have got egalikni bildiradi: I have got a bicycle — Menda velosiped bor. I, you, we, they bilan have got; he, she, it bilan has got ishlatiladi.\n\nInkor: I have not got a car. She has not got a cat. Qisqa shakllar haven’t got va hasn’t got. Savolda have yoki has oldinga chiqadi: Have you got a pencil? Has he got a brother?\n\nHave got dan keyingi buyum birlik bo‘lsa, a yoki an kerak bo‘lishi mumkin: a book, an apple. Ko‘plikda bu artikllar ishlatilmaydi: two books. Savolga Yes, I have. yoki No, I haven’t. kabi qisqa javob beriladi.',
      'She has got a blue bag.\nHas she got a blue bag? — Yes, she has.\nThey have got two bicycles. — They haven’t got a car.',
      [
        txt('I ___ got a bicycle.', 'have', 'I bilan have got.'),
        mc('She ___ got a cat.', ['has', 'have', 'is', 'are'], 'has', 'She bilan has got.'),
        tf('They has got books — to‘g‘ri gap.', false, 'They have got books bo‘lishi kerak.'),
        txt('___ you got a pencil?', 'have', 'Savolda Have you got...?'),
        mc(
          'He has not got a car. Qisqa shaklini tanlang.',
          [
            'He hasn’t got a car.',
            'He haven’t got a car.',
            'He isn’t got a car.',
            'He don’t got a car.',
          ],
          'He hasn’t got a car.',
          'Has not → hasn’t.',
        ),
        txt(
          'Have you got a book? — Yes, I ___.',
          'have',
          'Have bilan berilgan savolga Yes, I have deb javob beriladi.',
        ),
      ],
    ),
    lesson(
      'Nouns: birlik va ko‘plik',
      'So‘zlarni ko‘paytiramiz',
      'Otlarning oddiy va ayrim maxsus ko‘plik shakllarini tuzing.',
      'Ko‘pchilik otlarning ko‘pligi -s bilan hosil bo‘ladi: book → books, pen → pens. -s, -x, -sh yoki -ch bilan tugagan ko‘p otlarga -es qo‘shiladi: box → boxes, watch → watches.\n\nUndosh + y bilan tugagan otlarda y o‘rniga i yozilib, -es qo‘shiladi: city → cities. Unli + y bo‘lsa, faqat -s: boy → boys.\n\nBa’zi otlarning ko‘pligi maxsus shaklga ega: child → children, man → men, woman → women. Bunday shakllarni misollar bilan yodda saqlang. Birlikdagi a book iborasi ko‘plikda books bo‘ladi; a artikli ko‘plik oldida ishlatilmaydi.',
      'One box → two boxes.\nOne city → three cities.\nOne child → four children.\nHar bir misolda avval otning oxirgi harflarini tekshiramiz.',
      [
        txt('Book otining ko‘plik shaklini yozing.', 'books', 'Book + s = books.'),
        mc(
          'Box ning ko‘plik shakli?',
          ['boxes', 'boxs', 'boxies', 'boxen'],
          'boxes',
          'X bilan tugagani uchun -es qo‘shiladi.',
        ),
        tf('Boy ning ko‘plik shakli boys.', true, 'Unli + y bo‘lgani uchun faqat -s qo‘shiladi.'),
        txt('City ning ko‘plik shaklini yozing.', 'cities', 'Undosh + y: y → i, keyin -es.'),
        txt(
          'Child ning ko‘plik shakli?',
          'children',
          'Child maxsus ko‘plik shakliga ega: children.',
        ),
        mc(
          'To‘g‘ri iborani tanlang.',
          ['two books', 'two book', 'a books', 'two child'],
          'two books',
          'Two dan keyin ko‘plik shakli kerak.',
        ),
      ],
    ),
    lesson(
      'Present Simple: kundalik odatlar',
      'Mening kundalik hayotim',
      'Oddiy hozirgi zamonda odatlarni tasvirlang.',
      'Present Simple muntazam takrorlanadigan ishlar uchun ishlatiladi. I read every day. We go to school on weekdays. I, you, we, they bilan fe’l oddiy shaklda keladi.\n\nHe, she, it bilan odatda -s qo‘shiladi: She reads. Go → goes, study → studies kabi shakllarga e’tibor bering. Inkor: I don’t play. She doesn’t play. Does ishlatilganda asosiy fe’l oddiy shaklga qaytadi.\n\nSavol: Do you like English? Does he play football? Every day, usually, often kabi iboralar odatni ko‘rsatadi. Aniq hozir sodir bo‘layotgan harakat boshqa zamon bilan ifodalanadi; bu darsda kundalik odatlarga e’tibor beramiz.',
      'I get up at seven. My sister gets up at seven too.\nDo you read every day? — Yes, I do.\nShe doesn’t watch TV in the morning.',
      [
        mc(
          'She ___ books every day.',
          ['reads', 'read', 'reading', 'is read'],
          'reads',
          'She bilan read + s.',
        ),
        tf('I plays football — to‘g‘ri gap.', false, 'I bilan play: I play football.'),
        txt('He ___ to school every day. (go)', 'goes', 'Go + es = goes.'),
        txt('___ you like English?', 'do', 'You bilan savolda Do.'),
        mc(
          'She does not ___ football.',
          ['play', 'plays', 'playing', 'played'],
          'play',
          'Does not dan keyin oddiy fe’l shakli.',
        ),
        txt(
          'She ___ English every day. (study)',
          'studies',
          'Undosh + y bilan tugagan study: studies.',
        ),
      ],
    ),
  ],
  6: [
    lesson(
      'Past Simple: yesterday and last week',
      'O‘tgan voqealar',
      'Tugallangan o‘tgan harakatni Past Simple bilan ifodalang.',
      'Past Simple o‘tmishda tugallangan harakatlar uchun ishlatiladi. Yesterday, last week, two days ago kabi iboralar vaqtni ko‘rsatadi. Oddiy fe’llarga -ed qo‘shiladi: play → played, visit → visited.\n\nAyrim fe’llar maxsus shaklga ega: go → went, see → saw, buy → bought. Inkor va savolda did ishlatilganda asosiy fe’l oddiy shaklda bo‘ladi: I didn’t go. Did you see him?\n\nBe fe’lining o‘tgan shakllari was va were: I was at home. They were at school. O‘tgan voqeani aytayotganda vaqt va fe’l shaklini moslang. “Did you went?” xato, chunki did allaqachon o‘tgan zamonni ko‘rsatmoqda.',
      'Last Saturday, Ali visited his grandmother. He went there by bus.\nDid he go by car? — No, he didn’t.\nHe didn’t stay overnight.',
      [
        txt('We ___ football yesterday. (play)', 'played', 'Play oddiy fe’l: played.'),
        mc(
          'I ___ to school yesterday.',
          ['went', 'go', 'goes', 'going'],
          'went',
          'Go ning Past Simple shakli went.',
        ),
        tf(
          'Did you went home? — to‘g‘ri savol.',
          false,
          'Did you go home? Asosiy fe’l oddiy shaklda.',
        ),
        txt('She did not ___ the film. (see)', 'see', 'Did not dan keyin see ishlatiladi.'),
        txt('They ___ at school yesterday. (be)', 'were', 'They bilan o‘tgan zamonda were.'),
        mc(
          'To‘g‘ri savolni tanlang.',
          [
            'Did she buy a book?',
            'Did she bought a book?',
            'Does she bought a book?',
            'Did she buying a book?',
          ],
          'Did she buy a book?',
          'Did + ega + fe’lning oddiy shakli.',
        ),
      ],
    ),
    lesson(
      'Present Continuous: hozir nima bo‘lyapti?',
      'Hozirgi harakat',
      'Am/is/are va -ing bilan davom etayotgan harakatni ayting.',
      'Present Continuous hozir yoki hozirgi davrda davom etayotgan harakatlar uchun ishlatiladi. Tuzilishi: ega + am/is/are + fe’l-ing. I am reading now. She is writing. They are playing.\n\nAm, is yoki are ni egaga mos tanlang. Faqat -ing qo‘shish yetmaydi: She reading emas, She is reading bo‘lishi kerak. Write → writing, run → running kabi imlo o‘zgarishlarini eslang.\n\nSavol tuzishda be egadan oldin keladi: Are they studying? Inkor: They are not studying. Present Simple odatni, Present Continuous esa davom etayotgan ishni ifodalaydi: I read every day, lekin I am reading now.',
      'Madina is doing her homework now.\nIs she watching TV? — No, she isn’t.\nHer brothers are playing outside.',
      [
        txt('I ___ reading now.', 'am', 'I bilan am.'),
        mc(
          'They ___ playing outside now.',
          ['are', 'is', 'am', 'do'],
          'are',
          'They bilan are + playing.',
        ),
        tf('She reading now — to‘g‘ri gap.', false, 'She is reading now bo‘lishi kerak.'),
        txt('Write fe’lining -ing shaklini yozing.', 'writing', 'Oxirgi e tushadi: writing.'),
        mc(
          'They are studying. Are bilan boshlanadigan savol shaklini tanlang.',
          ['Are they studying?', 'Do they studying?', 'Is they studying?', 'They are studying?'],
          'Are they studying?',
          'Are egadan oldinga chiqadi.',
        ),
        txt(
          'Run fe’lining -ing shaklini yozing.',
          'running',
          'Oxirgi n ikki marta yoziladi: running.',
        ),
      ],
    ),
    lesson(
      'Countable nouns, some va any',
      'Ovqat va xarid',
      'Sanash mumkin bo‘lgan otlar bilan some va any ni farqlang.',
      'Countable otlarni donalab sanash mumkin: one apple, two apples. Uncountable otlar odatda bu shaklda sanalmaydi: water, rice, milk. Ular uchun a glass of water kabi o‘lchov yoki idish nomini ishlatamiz.\n\nSome ko‘pincha tasdiq gaplarda ishlatiladi: There are some apples. Any ko‘pincha inkor va oddiy savollarda keladi: There aren’t any apples. Are there any apples? Taklif va iltimoslarda savol bo‘lsa ham some ishlatilishi mumkin: Would you like some water?\n\nHow many sanaladigan ko‘plik otlar bilan, how much sanalmaydigan otlar bilan ishlatiladi. How many apples? How much water? Kontekstni va ot turini birga tekshiring.',
      'There are some apples in the bag. There isn’t any milk.\nHow many apples are there? — Three.\nWould you like some water? — Yes, please.',
      [
        mc(
          'Qaysi otni donalab sanash mumkin?',
          ['apple', 'water', 'rice', 'milk'],
          'apple',
          'One apple, two apples deyish mumkin.',
        ),
        tf('How many water? — odatiy to‘g‘ri savol.', false, 'Water sanalmaydi: How much water?'),
        txt(
          'There are ___ apples. Tasdiq gap uchun some yoki any ni tanlang.',
          'some',
          'Tasdiq gaplarda odatda some.',
        ),
        mc(
          'There isn’t ___ milk.',
          ['any', 'many', 'a', 'an'],
          'any',
          'Inkor gapda any milk ishlatiladi.',
        ),
        txt(
          '___ many books have you got? Birinchi so‘zni yozing.',
          'how',
          'How many sanaladigan ko‘plik ot bilan.',
        ),
        mc(
          'Water sanalmaydigan ot bo‘lgan, some bilan suv taklif qilayotgan gapni tanlang.',
          [
            'Would you like some water?',
            'Would you like many water?',
            'Would you like a water?',
            'Would you like an water?',
          ],
          'Would you like some water?',
          'Taklif savollarida some ishlatilishi mumkin.',
        ),
      ],
    ),
    lesson(
      'Comparatives va superlatives',
      'Taqqoslash',
      'Ikki narsani taqqoslash va guruhdagi eng yuqori xususiyatni ayting.',
      'Comparative ikki narsani taqqoslaydi: tall → taller, big → bigger. Taqqoslashda than ishlatiladi: Ali is taller than Sardor. Superlative guruhdagi eng yuqori xususiyatni bildiradi: the tallest, the biggest.\n\nUzun sifatlarga more yoki the most qo‘shiladi: more interesting, the most interesting. Undosh + y bilan tugaganda y → i: happy → happier → the happiest.\n\nGood va bad maxsus shakllarga ega: good → better → the best; bad → worse → the worst. More better deyilmaydi, chunki better allaqachon qiyosiy shakl. Superlative oldidan odatda the ishlatiladi.',
      'This bag is cheaper than that bag.\nIt is the cheapest bag in the shop.\nThis is the most interesting book in our class library.',
      [
        txt('Tall sifatining qiyosiy shakli?', 'taller', 'Tall + er = taller.'),
        mc(
          'Good ning orttirma darajasi?',
          ['the best', 'the goodest', 'the better', 'the most good'],
          'the best',
          'Good → better → the best.',
        ),
        tf('More better — to‘g‘ri shakl.', false, 'Better yetarli; more qo‘shilmaydi.'),
        txt('This bag is cheaper ___ that bag.', 'than', 'Ikki narsani taqqoslashda than.'),
        txt(
          'Happy ning orttirma shaklini the bilan yozing.',
          'the happiest',
          'Y → i: the happiest.',
        ),
        mc(
          'Interesting sifatining orttirma darajasi?',
          [
            'the most interesting',
            'the interestingest',
            'more interesting',
            'the more interesting',
          ],
          'the most interesting',
          'Uzun sifat bilan the most ishlatiladi.',
        ),
      ],
    ),
    lesson(
      'Be going to: kelajak rejalari',
      'Rejalarimiz',
      'Oldindan qilingan reja uchun be going to ishlating.',
      'Be going to oldindan o‘ylangan kelajak rejasini ifodalaydi. Tuzilishi: ega + am/is/are + going to + fe’lning oddiy shakli. I am going to visit my aunt. She is going to read a book.\n\nBe egaga mos kelishi kerak. They are going to play. Savol: Are they going to play? Inkor: They are not going to play. Going to dan keyin fe’lga -s yoki -ing qo‘shilmaydi.\n\nTomorrow, next week, on Saturday kabi vaqt iboralari rejaning qachon bajarilishini ko‘rsatadi. Going to bilan reja va hozirgi harakatni adashtirmang: I am reading now hozirgi harakat, I am going to read tonight esa kelajak rejasi.',
      'We are going to visit Samarkand next week.\nAre we going to travel by train? — Yes, we are.\nWe are not going to travel by car.',
      [
        txt('I ___ going to read tonight.', 'am', 'I bilan am.'),
        mc(
          'She is going to ___ a book.',
          ['read', 'reads', 'reading', 'readed'],
          'read',
          'Going to dan keyin oddiy fe’l.',
        ),
        tf('They is going to play — to‘g‘ri gap.', false, 'They are going to play.'),
        txt('___ they going to visit their aunt?', 'are', 'Savol Are they going to...?'),
        mc(
          'Kelajak rejasini bildirgan gapni tanlang.',
          [
            'I am going to study tomorrow.',
            'I studied yesterday.',
            'I am studying now.',
            'I study every day.',
          ],
          'I am going to study tomorrow.',
          'Going to + tomorrow oldindan qilingan rejani bildiradi.',
        ),
        txt(
          'We are not going to travel. “are not” ning qisqa shakli?',
          "aren't|aren’t",
          'Are not → aren’t.',
        ),
      ],
    ),
    lesson(
      'Giving directions: yo‘lni tushuntirish',
      'Shahar bo‘ylab',
      'Go straight, turn left va turn right ko‘rsatmalarini tushuning.',
      'Yo‘lni so‘rash uchun Excuse me, where is the library? deyish mumkin. Go straight — to‘g‘ri boring. Turn left — chapga buriling. Turn right — o‘ngga buriling.\n\nJoylashuvni aytishda next to — yonida, opposite — qarshisida, between — orasida ishlatiladi. Between odatda ikki joy nomi bilan keladi: between the school and the park.\n\nKo‘rsatmalarni tartib bilan o‘qing. Masalan, avval to‘g‘ri yurish, keyin chapga burilish talab qilinishi mumkin. Left va right ni odam qaysi tomonga qarab turganiga nisbatan tushunamiz. Muloyim so‘rash va rahmat aytish suhbatni yaxshilaydi.',
      'A: Excuse me, where is the library?\nB: Go straight and turn left. The library is next to the school.\nA: Thank you!\nB: You’re welcome.',
      [
        mc(
          'Turn left nimani anglatadi?',
          ['Chapga buriling', 'O‘ngga buriling', 'To‘xtang', 'Ortga qayting'],
          'Chapga buriling',
          'Left — chap.',
        ),
        tf('Opposite so‘zi “qarshisida” degani.', true, 'Opposite — boshqa tomonda, qarshisida.'),
        txt('“O‘ng” so‘zini inglizcha yozing.', 'right', 'Right — o‘ng.'),
        mc(
          '“Yonida” ma’nosini bildiradigan ibora?',
          ['next to', 'between', 'behind', 'far from'],
          'next to',
          'Next to — yonida.',
        ),
        txt(
          'The park is ___ the school and the library. “Orasida” ma’nosida to‘ldiring.',
          'between',
          'Between ikki joy orasini bildiradi.',
        ),
        mc(
          'Yo‘lni muloyim so‘rash uchun qaysi gap mos?',
          [
            'Excuse me, where is the library?',
            'You library go!',
            'Library you?',
            'Turn me library.',
          ],
          'Excuse me, where is the library?',
          'Excuse me suhbatni muloyim boshlaydi.',
        ),
      ],
    ),
  ],
  7: [
    lesson(
      'Present Perfect: tajriba va natija',
      'Tajriba haqida gapiramiz',
      'Have/has va past participle bilan hayotiy tajribani ayting.',
      'Present Perfect ega + have/has + past participle shaklida tuziladi. I have visited Samarkand. She has finished her homework. Gap ko‘pincha o‘tgan ishning hozirgi natijasi yoki tajribasiga e’tibor beradi.\n\nI, you, we, they bilan have; he, she, it bilan has ishlatiladi. Past participle oddiy fe’llarda -ed, ayrim fe’llarda maxsus shakl: see → seen, go → gone, be → been. Tajriba haqida been to ishlatiladi: I have been to Bukhara.\n\nEver “hech qachon tajribangiz bo‘lganmi?” savollarida, never esa tajriba yo‘qligini bildiradi. Aniq tugallangan vaqt yesterday bilan odatda Past Simple ishlatiladi. Present Perfect da esa vaqtni aniq belgilash shart emas.',
      'Have you ever been to Samarkand? — Yes, I have.\nShe has already finished her homework.\nI saw the film yesterday. — Aniq o‘tgan vaqt, shuning uchun Past Simple.',
      [
        txt(
          'She ___ finished her homework. Present Perfect uchun have yoki has ni yozing.',
          'has',
          'She bilan has + finished.',
        ),
        mc(
          'See fe’lining past participle shakli?',
          ['seen', 'saw', 'see', 'seeing'],
          'seen',
          'See → saw → seen.',
        ),
        tf(
          'Yesterday bilan tugallangan voqea uchun odatda Past Simple ishlatiladi.',
          true,
          'Yesterday aniq o‘tgan vaqtni bildiradi.',
        ),
        txt(
          'Have you ___ been to Bukhara? “Hech tajribangiz bo‘lganmi” savoli.',
          'ever',
          'Ever tajriba haqidagi savollarda ishlatiladi.',
        ),
        mc(
          'To‘g‘ri gapni tanlang.',
          [
            'I have been to Samarkand twice.',
            'I have went to Samarkand twice.',
            'I has been to Samarkand twice.',
            'I have be to Samarkand twice.',
          ],
          'I have been to Samarkand twice.',
          'I + have + been to tajribani bildiradi.',
        ),
        txt(
          'They have ___ this film. (see ning past participle shakli)',
          'seen',
          'They have seen this film.',
        ),
      ],
    ),
    lesson(
      'Past Continuous va uzilgan harakat',
      'Voqealar davomida',
      'O‘tmishda davom etayotgan ishni was/were + -ing bilan ayting.',
      'Past Continuous o‘tmishdagi ma’lum paytda davom etayotgan harakatni bildiradi. Tuzilishi: was/were + fe’l-ing. I was reading at eight last night. They were playing at five.\n\nI, he, she, it bilan was; you, we, they bilan were ishlatiladi. Davom etayotgan harakatni boshqa qisqa harakat to‘xtatishi mumkin: I was reading when the phone rang. Reading davom etayotgan ish, rang esa shu paytda sodir bo‘lgan voqea.\n\nWhile ko‘pincha ikki davomiy ishni bog‘laydi: While I was reading, my sister was drawing. When va while ni tarjimasi bilangina emas, gapdagi harakatlar vazifasiga qarab tushuning.',
      'At seven, Madina was doing homework. Her brothers were playing.\nShe was writing when the phone rang.\nRang Past Simple, was writing Past Continuous.',
      [
        txt('I ___ reading at eight last night.', 'was', 'I bilan was.'),
        mc(
          'They ___ playing at five yesterday.',
          ['were', 'was', 'are', 'is'],
          'were',
          'They bilan were.',
        ),
        tf('He were sleeping — to‘g‘ri gap.', false, 'He was sleeping bo‘lishi kerak.'),
        txt(
          'I was reading when the phone ___. (ring ning Past Simple shakli)',
          'rang',
          'Ring → rang → rung; qisqa voqea Past Simple da.',
        ),
        mc(
          'O‘tmishda davom etayotgan harakatni tanlang.',
          ['She was writing.', 'She writes every day.', 'She has written.', 'She will write.'],
          'She was writing.',
          'Was + writing davomiy o‘tgan harakat.',
        ),
        txt(
          'While I was reading, she ___ drawing. Past Continuous uchun was yoki were ni yozing.',
          'was',
          'She bilan was drawing.',
        ),
      ],
    ),
    lesson(
      'First Conditional: shart va natija',
      'Kelajakdagi ehtimollar',
      'If + Present Simple va will bilan kelajakdagi shartli gap tuzing.',
      'First Conditional kelajakda sodir bo‘lishi mumkin bo‘lgan shart va uning natijasini ifodalaydi. Asosiy tuzilma: If + Present Simple, will + fe’lning oddiy shakli. If it rains tomorrow, we will stay at home.\n\nIf qismida odatda will ishlatilmaydi: If it will rain emas, If it rains. Natija qismida will dan keyingi fe’l oddiy shaklda bo‘ladi.\n\nQismlar tartibi o‘zgarishi mumkin: We will stay at home if it rains tomorrow. If qismi oldin kelsa, odatda vergul bilan ajratiladi. Bu darsda umumiy odat emas, kelajakdagi mumkin bo‘lgan vaziyatni tasvirlaymiz.',
      'If I finish my homework, I will play football.\nI will play football if I finish my homework.\nIkkalasida ham shart — uy vazifasini tugatish; natija — futbol o‘ynash.',
      [
        txt(
          'If it ___ tomorrow, we will stay at home. (rain)',
          'rains',
          'If qismida Present Simple: it rains.',
        ),
        mc(
          'First Conditional tuzilmasini tanlang.',
          [
            'If + Present Simple, will + verb',
            'If + will, will + verb',
            'If + Past Simple, was + verb',
            'If + verb-ing, has + verb',
          ],
          'If + Present Simple, will + verb',
          'Kelajakdagi mumkin bo‘lgan shart va natija.',
        ),
        tf(
          'If I will finish my homework, I will play — bu darsdagi standart tuzilma.',
          false,
          'If I finish my homework, I will play bo‘lishi kerak.',
        ),
        txt(
          'If you study, you will ___ more. (learn)',
          'learn',
          'Will dan keyin fe’l oddiy shaklda.',
        ),
        mc(
          'To‘g‘ri First Conditional gapni tanlang.',
          [
            'If she comes, we will start.',
            'If she will comes, we start.',
            'If she come, we will starts.',
            'If she coming, we started.',
          ],
          'If she comes, we will start.',
          'If qismida comes, natijada will start.',
        ),
        txt(
          'We ___ stay at home if it rains tomorrow. First Conditional bo‘yicha to‘ldiring.',
          'will',
          'Natija qismida will stay ishlatiladi.',
        ),
      ],
    ),
    lesson(
      'Relative clauses: who, which, where',
      'Odam va joyni tasvirlash',
      'Aniqlovchi gap bilan odam, narsa va joyni izohlang.',
      'Relative clause ot haqida qo‘shimcha ma’lumot beradi. A teacher is a person who helps pupils. Who odamlar uchun ishlatiladi. This is a book which I like. Which narsalar uchun ishlatiladi.\n\nAniqlovchi gaplarda that ko‘pincha who yoki which o‘rnida kelishi mumkin: the book that I like. Where joyni izohlaydi: This is the school where I study.\n\nMos so‘zni tanlash uchun izohlanayotgan otga qarang: odammi, narsami yoki joymi? So‘zlar tartibini ham tekshiring. The boy who plays football... iborasida who ning ortidan fe’l kelib, boy haqida ma’lumot beradi.',
      'This is the girl who won the prize.\nThis is the book which I bought.\nThis is the library where we read.\nThe book that I bought ham to‘g‘ri.',
      [
        mc(
          'A teacher is a person ___ helps pupils.',
          ['who', 'where', 'when', 'whose'],
          'who',
          'Person odam bo‘lgani uchun who.',
        ),
        tf(
          'Which odatda narsalarni izohlash uchun ishlatiladi.',
          true,
          'Masalan, a book which I like.',
        ),
        txt(
          'This is the library ___ we read. Joyni bildiradigan who, which yoki where dan birini yozing.',
          'where|in which',
          'Joy uchun where; in which ham mos keladi.',
        ),
        mc(
          'This is the phone ___ I use.',
          ['which', 'where', 'who', 'when'],
          'which',
          'Phone narsa, which ishlatiladi.',
        ),
        txt(
          'The book ___ I bought is interesting. Which bilan almashadigan so‘zni yozing.',
          'that',
          'Aniqlovchi gapda that which o‘rnida kelishi mumkin.',
        ),
        mc(
          'Odamni izohlovchi to‘g‘ri iborani tanlang.',
          [
            'the boy who plays football',
            'the boy where plays football',
            'the boy when plays football',
            'the boy which football',
          ],
          'the boy who plays football',
          'Who odam haqida izoh beradi.',
        ),
      ],
    ),
    lesson(
      'Must, mustn’t va don’t have to',
      'Qoidalar va majburiyat',
      'Majburiyat, taqiq va majburiyat yo‘qligini farqlang.',
      'Must kuchli majburiyatni bildiradi: You must follow the rules. Mustn’t taqiqni bildiradi: You mustn’t share your password. Must va mustn’t dan keyin fe’l oddiy shaklda ishlatiladi.\n\nDon’t have to majburiyat yo‘qligini bildiradi. You don’t have to come early — erta kelishingiz shart emas, lekin mumkin. Bu taqiq emas. He yoki she bilan doesn’t have to ishlatiladi.\n\nMustn’t va don’t have to ni adashtirmang: birinchisida amal taqiqlangan, ikkinchisida esa amalni bajarish shart emas. Qoidani tushunish uchun vaziyatni o‘qing va ma’noni aniqlang.',
      'You must bring your notebook. — Daftaringizni olib kelishingiz kerak.\nYou mustn’t use someone else’s password. — Birovning parolini ishlatish taqiqlangan.\nYou don’t have to bring a laptop. — Noutbuk olib kelishingiz shart emas.',
      [
        mc(
          '“Taqiqlangan” ma’nosini qaysi shakl bildiradi?',
          ['mustn’t', 'don’t have to', 'can', 'may'],
          'mustn’t',
          'Mustn’t taqiqni bildiradi.',
        ),
        tf('Don’t have to harakatni taqiqlaydi.', false, 'U majburiyat yo‘qligini bildiradi.'),
        txt(
          'She ___ have to bring a laptop. Inkor shaklini to‘ldiring.',
          "doesn't|doesn’t|does not",
          'She bilan doesn’t have to.',
        ),
        mc(
          'You must ___ the rules.',
          ['follow', 'follows', 'following', 'followed'],
          'follow',
          'Must dan keyin oddiy fe’l.',
        ),
        txt('“Must not” ning qisqa shaklini yozing.', "mustn't|mustn’t", 'Must not → mustn’t.'),
        mc(
          '“Erta kelishingiz shart emas” ma’nosidagi gap?',
          [
            'You don’t have to come early.',
            'You mustn’t come early.',
            'You must come early.',
            'You cannot come early.',
          ],
          'You don’t have to come early.',
          'Don’t have to majburiyat yo‘qligini bildiradi.',
        ),
      ],
    ),
    lesson(
      'Reading: maktab kitob klubi',
      'Matnni tushunish',
      'Qisqa matndan dalil toping va xulosani matnga asoslang.',
      'Matnni o‘qishda avval umumiy mazmunni, keyin savol uchun kerakli tafsilotni topamiz. Savolga taxmin bilan emas, matndagi dalil bilan javob bering.\n\nMatn: Our reading club meets on Wednesday. There are twelve members. We meet in the school library from four o’clock to a quarter to five. Each member brings one book. We share ideas after reading. Madina likes adventure stories, but Ali prefers books about space. We never write in library books because other pupils will use them too.\n\nA quarter to five — 4:45. Savollarni o‘qib, kun, joy, vaqt va qahramonlarning qiziqishlarini alohida ajrating. Dalildan kelib chiqadigan xulosa bilan matnda umuman aytilmagan ma’lumotni farqlang.',
      'Savol: Where does the club meet?\nDalil: “in the school library”.\nJavob: In the school library.\nSavol: Does Ali prefer adventure stories? — No, he prefers books about space.',
      [
        mc(
          'What day does the club meet?',
          ['Wednesday', 'Monday', 'Friday', 'Sunday'],
          'Wednesday',
          'Matnda “meets on Wednesday” deyilgan.',
        ),
        tf(
          'Ali prefers books about space.',
          true,
          'Matnda Ali kosmos haqidagi kitoblarni afzal ko‘rishi aytilgan.',
        ),
        num('How many members are in the club?', 12, 'Twelve members — 12 ta a’zo.'),
        txt(
          'Where does the club meet? Faqat joy nomini inglizcha yozing.',
          'school library|the school library|in the school library',
          'Ular maktab kutubxonasida uchrashadi.',
        ),
        num(
          'The club meets from 4:00 to 4:45. How many minutes is the meeting?',
          45,
          '4:00 dan 4:45 gacha 45 daqiqa.',
        ),
        mc(
          'Why don’t they write in library books?',
          [
            'Other pupils will use them too.',
            'They have no pencils.',
            'The club has no books.',
            'They only read at home.',
          ],
          'Other pupils will use them too.',
          'Oxirgi gapda boshqa o‘quvchilar ham kitoblardan foydalanishi aytilgan.',
        ),
      ],
    ),
  ],
};
