import { lesson, mc, tf, num, txt, type GradeCurriculum } from './types';

export const informatics: GradeCurriculum = {
  5: [
    lesson(
      'Axborot turlari va sezgi organlari',
      'Axborot olami',
      'Matn, tasvir va tovush ko‘rinishidagi axborotni farqlang.',
      'Axborot atrofimizdagi narsalar va voqealar haqida bilishga yordam beradi. Uni matn, son, tasvir, tovush va video ko‘rinishida uchratamiz. Jadvaldagi baho sonli, kitobdagi izoh matnli, xarita esa tasvirli axborotga misol bo‘ladi.\n\nOdam ko‘rish, eshitish, hid, ta’m va teginish orqali ma’lumot oladi. Kompyuter bu axborotni qurilmalar yordamida qabul qiladi: mikrofon tovushni, kamera tasvirni kiritadi.\n\nBir xabar bir nechta ko‘rinishni birlashtirishi mumkin. Masalan, videodars tasvir va tovushni birga beradi. Axborot turini aniqlashda xabar mazmuni bilan uni taqdim qilish usulini farqlang.',
      'Maktab tadbiri haqida uch xabar:\n1. E’lon matni — matnli axborot.\n2. Tadbir fotosurati — tasvirli axborot.\n3. Boshlovchining nutqi — tovushli axborot.',
      [
        mc(
          'Fotosurat qanday axborot ko‘rinishi?',
          ['Tasvirli', 'Faqat sonli', 'Tovushli', 'Hidsiz'],
          'Tasvirli',
          'Fotosurat tasvir orqali ma’lumot beradi.',
        ),
        tf(
          'Bir xabar bir nechta axborot ko‘rinishini birlashtirishi mumkin.',
          true,
          'Videoda tasvir va tovush birga keladi.',
        ),
        txt(
          'Tovushni kompyuterga kiritadigan qurilma nomini yozing.',
          'mikrofon',
          'Mikrofon tovushni qabul qiladi.',
        ),
        mc(
          'Baholar jadvalidagi 5 raqami qanday axborot?',
          ['Sonli', 'Tovushli', 'Hidli', 'Video'],
          'Sonli',
          'Baho son yordamida ifodalangan.',
        ),
        mc(
          'Xaritani ko‘rish orqali qaysi sezgi bilan axborot olamiz?',
          ['Ko‘rish', 'Ta’m bilish', 'Hid bilish', 'Eshitish'],
          'Ko‘rish',
          'Xarita ko‘z bilan o‘qiladigan tasvirdir.',
        ),
        mc(
          'Videodars odatda qaysi ikki ko‘rinishni birlashtiradi?',
          ['Tasvir va tovush', 'Faqat hid va ta’m', 'Faqat son', 'Faqat teginish'],
          'Tasvir va tovush',
          'Video tasvirni, ovoz esa tovushni beradi.',
        ),
      ],
    ),
    lesson(
      'Kompyuterning kiritish va chiqarish qurilmalari',
      'Qurilmalar',
      'Qurilmalarni vazifasiga qarab ajrating.',
      'Kiritish qurilmasi ma’lumotni kompyuterga uzatadi. Klaviatura matn, sichqoncha buyruq, mikrofon tovush kiritadi. Chiqarish qurilmasi natijani foydalanuvchiga beradi: monitor tasvirni, karnay tovushni, printer qog‘ozdagi nusxani chiqaradi.\n\nKompyuter ma’lumotni qayta ishlaydi va saqlashi ham mumkin. Xotira yoki saqlash qurilmasi fayllarni keyinroq foydalanish uchun saqlaydi. Qurilmaning tashqi ko‘rinishiga emas, bajarayotgan vazifasiga qarang.\n\nAyrim qurilmalar ikkala vazifani ham bajaradi. Sensorli ekran tasvirni chiqaradi va barmoq tegishini kiritadi. Qurilma ulash yoki nosozlik bo‘lsa, o‘qituvchi ko‘rsatmasiga amal qiling.',
      'Hujjat yozish zanjiri:\nKlaviatura → matnni kiritish.\nKompyuter → qayta ishlash.\nMonitor → natijani ko‘rsatish.\nPrinter → qog‘ozga chiqarish.',
      [
        mc(
          'Klaviatura qaysi turdagi qurilma?',
          ['Kiritish', 'Faqat chiqarish', 'Faqat saqlash', 'Qog‘ozli'],
          'Kiritish',
          'Klaviatura matn va buyruq kiritadi.',
        ),
        tf('Printer ma’lumotni qog‘ozga chiqaradi.', true, 'Printer chiqarish qurilmasidir.'),
        txt(
          'Tasvirni ekranda ko‘rsatadigan qurilma nomi?',
          'monitor|ekran',
          'Monitor tasvirni ko‘rsatadi.',
        ),
        mc(
          'Tovushni chiqaradigan qurilma?',
          ['Karnay', 'Mikrofon', 'Klaviatura', 'Sichqoncha'],
          'Karnay',
          'Karnay tovush chiqaradi, mikrofon esa kiritadi.',
        ),
        mc(
          'Sensorli ekran qanday vazifalar bajarishi mumkin?',
          [
            'Kiritish va chiqarish',
            'Faqat qog‘ozga chiqarish',
            'Faqat saqlash',
            'Faqat tovushni yozish',
          ],
          'Kiritish va chiqarish',
          'Tasvir chiqaradi va teginishni qabul qiladi.',
        ),
        mc(
          'Hujjatni yozish va qog‘ozga olish uchun qaysi juftlik mos?',
          [
            'Klaviatura va printer',
            'Karnay va mikrofon',
            'Monitor va karnay',
            'Sichqoncha va kamera',
          ],
          'Klaviatura va printer',
          'Klaviatura bilan kiritamiz, printer bilan chiqaramiz.',
        ),
      ],
    ),
    lesson(
      'Fayl, papka va tushunarli nomlar',
      'Raqamli tartib',
      'Fayllarni papkalarda tartiblang va kengaytmani taning.',
      'Fayl kompyuterda saqlangan hujjat, rasm yoki boshqa ma’lumotdir. Papka esa fayl va boshqa papkalarni tartiblash uchun xizmat qiladi. Bitta papkada bir nechta fayl bo‘lishi mumkin.\n\nFaylning nomi mazmunini tushuntirsin: matematika_mashq_1.docx. Kengaytma nuqtadan keyingi qism bo‘lib, format haqida ma’lumot beradi: .txt matn, .png rasm, .pdf hujjat formati. Kengaytmani shunchaki almashtirish faylni boshqa formatga aylantirmaydi.\n\nKerakli ishni topish uchun fanlar bo‘yicha papka yarating. O‘chirishdan oldin fayl nima ekanini tekshiring. Muhim faylning zaxira nusxasi ma’lumotni yo‘qotmaslikka yordam beradi.',
      'OYLA / Matematika / kasrlar_mashq.pdf\nOYLA — asosiy papka, Matematika — ichki papka, kasrlar_mashq.pdf — fayl.\nNomidan fan va mavzuni bilish mumkin.',
      [
        mc(
          'Fayllarni tartiblash uchun nima ishlatiladi?',
          ['Papka', 'Karnay', 'Monitor yorqinligi', 'Parol harfi'],
          'Papka',
          'Papka fayllarni guruhlaydi.',
        ),
        tf(
          'Fayl kengaytmasini o‘zgartirish uning formatini avtomatik aylantiradi.',
          false,
          'Formatni o‘zgartirish uchun mos eksport yoki konvertatsiya kerak.',
        ),
        txt(
          'rasm.png faylining kengaytmasini nuqtasi bilan yozing.',
          '.png',
          'Nuqtadan keyingi png — format belgisi.',
        ),
        mc(
          'Qaysi nom tushunarliroq?',
          ['matematika_kasrlar.pdf', 'fayl999', 'yangi_yangi', 'aaa'],
          'matematika_kasrlar.pdf',
          'Nomdan fan va mavzu bilinadi.',
        ),
        mc(
          'Muhim ish yo‘qolmasligi uchun qaysi amal foydali?',
          [
            'Zaxira nusxa saqlash',
            'Hamma faylni o‘chirish',
            'Kengaytmani yashirish',
            'Nomlarni bir xil qilish',
          ],
          'Zaxira nusxa saqlash',
          'Zaxira nusxa asl fayl yo‘qolsa yordam beradi.',
        ),
        num(
          'Papka ichida 4 ta matn va 3 ta rasm fayli bor. Jami nechta fayl?',
          7,
          '4 + 3 = 7 ta fayl.',
        ),
      ],
    ),
    lesson(
      'Klaviatura va matn kiritish',
      'Matn bilan ishlash',
      'Bo‘shliq, yangi abzas va o‘chirish tugmalarini farqlang.',
      'Klaviatura matn va buyruqlar kiritish uchun ishlatiladi. Space so‘zlar orasida bo‘shliq qo‘yadi. Enter matn protsessorida yangi abzas boshlaydi. Shift bilan harfni bosish katta harf yozishga yordam beradi.\n\nBackspace kursorning chapidagi belgini, Delete odatda o‘ngidagi belgini o‘chiradi. Kursor matnga keyingi belgi qayerda qo‘shilishini ko‘rsatadi. Matnni o‘zgartirishdan oldin kursor yoki tanlangan qismni tekshiring.\n\nHar bir satr oxirida Enter bosish shart emas: dastur ko‘pincha satrni o‘zi ko‘chiradi. So‘zlar orasida bitta bo‘shliq ishlating. Tahrirdan keyin hujjatni saqlashni eslang.',
      '“OYLA bilim beradi.” yozamiz.\nSo‘zlar orasida Space, yangi abzas uchun Enter.\nXato belgini o‘chirishda kursorning joyiga qarab Backspace yoki Delete tanlanadi.',
      [
        mc(
          'So‘zlar orasiga bo‘shliq qo‘yadigan tugma?',
          ['Space', 'Enter', 'Delete', 'Esc'],
          'Space',
          'Space bo‘shliq kiritadi.',
        ),
        tf(
          'Backspace odatda kursor chapidagi belgini o‘chiradi.',
          true,
          'Chapdagi belgi o‘chiriladi.',
        ),
        txt(
          'Matn protsessorida yangi abzas boshlaydigan tugma nomi?',
          'enter',
          'Enter yangi abzas boshlaydi.',
        ),
        mc(
          'Katta harfni vaqtincha yozish uchun qaysi tugma bilan harf bosiladi?',
          ['Shift', 'Space', 'Delete', 'Tab'],
          'Shift',
          'Shift + harf katta harf kiritadi.',
        ),
        mc(
          'Kursor nimani ko‘rsatadi?',
          [
            'Keyingi belgi kiritiladigan joyni',
            'Faqat fayl hajmini',
            'Internet tezligini',
            'Qurilma narxini',
          ],
          'Keyingi belgi kiritiladigan joyni',
          'Kursor matndagi kiritish joyini bildiradi.',
        ),
        tf(
          'Matnning har bir avtomatik satri oxirida Enter bosish zarur.',
          false,
          'Dastur satrni avtomatik ko‘chiradi; Enter yangi abzas uchun kerak.',
        ),
      ],
    ),
    lesson(
      'Grafik muharrir: shakl va rang',
      'Tasvir yaratish',
      'Shakl, kontur va to‘ldirish vositalarini tanlang.',
      'Grafik muharrir rasm chizish va tasvirni tahrirlashga xizmat qiladi. Qalam erkin chiziq chizadi, shakl vositasi esa to‘rtburchak yoki aylana kabi geometrik ko‘rinishni yaratadi.\n\nKontur shaklning chegarasi, to‘ldirish esa uning ichki rangidir. Faqat kontur rangini o‘zgartirish ichki rangni o‘zgartirmasligi mumkin. Asbobni tanlashdan oldin qaysi qismni o‘zgartirmoqchi ekaningizni aniqlang.\n\nNoto‘g‘ri amalni bekor qilish tahrirni yengillashtiradi. Rasmni saqlaganda mos format va tushunarli nom tanlang. Darsning maqsadi muayyan dastur tugmasini yodlash emas, tasvir yaratish amallarini tushunishdir.',
      'Uycha chizamiz:\n1. Devor uchun to‘rtburchak.\n2. Tom uchun uchburchak.\n3. Deraza uchun kichik kvadrat.\n4. Shakllarning ichini rang bilan to‘ldirish.\n5. Natijani uycha.png deb saqlash.',
      [
        mc(
          'Erkin chiziq chizish uchun qaysi vosita mos?',
          ['Qalam', 'Matnni saqlash', 'Fayl papkasi', 'Printer navbati'],
          'Qalam',
          'Qalam erkin chiziq chizadi.',
        ),
        tf('Kontur shaklning chegarasidir.', true, 'Kontur tashqi chiziqni bildiradi.'),
        txt(
          'Shaklning ichki rangini berish amali nima? “To‘ldirish” yoki “kontur”.',
          "to‘ldirish|to'ldirish|toldirish",
          'To‘ldirish ichki rangni o‘zgartiradi.',
        ),
        mc(
          'Deraza chizish uchun qaysi shakl qulay?',
          ['Kvadrat', 'Faqat egri chiziq', 'Tovush', 'Abzas'],
          'Kvadrat',
          'Kvadrat deraza shakliga mos kelishi mumkin.',
        ),
        mc(
          'Rasm uchun mos fayl nomini tanlang.',
          ['uycha.png', 'uycha.mp3', 'uycha.txt', 'uycha.wav'],
          'uycha.png',
          'PNG rasm formatidir.',
        ),
        mc(
          'Xato chiziqni bekor qilish uchun qaysi amal kerak?',
          [
            'Oxirgi amalni bekor qilish',
            'Barcha fayllarni o‘chirish',
            'Kompyuterni uzib qo‘yish',
            'Parolni tarqatish',
          ],
          'Oxirgi amalni bekor qilish',
          'Undo oxirgi tahrirni bekor qilishga xizmat qiladi.',
        ),
      ],
    ),
    lesson(
      'Raqamli xavfsizlik va shaxsiy ma’lumot',
      'Xavfsiz odatlar',
      'Parol va shaxsiy ma’lumotni himoya qilishga mos qaror tanlang.',
      'Parol hisobingizga kirishni himoya qiladi. Uni begonalarga yubormang va bir xil parolni hamma xizmatda ishlatmang. Uzun, noyob parol qisqa va taxmin qilinadigan paroldan yaxshiroq.\n\nNotanish xabar sovrin yoki shoshilinch yordam va’da qilib, parol so‘rashi mumkin. Bunday holatda xabar yuboruvchisi va manbasini tekshiring. Shaxsiy manzil yoki telefon kabi ma’lumotni ulashishdan oldin ishonchli katta bilan maslahat qiling.\n\nUmumiy qurilmada ish tugagach hisobdan chiqing. Sizni bezovta qiladigan xabar bo‘lsa, ishonchli kattaga yoki o‘qituvchiga ko‘rsating. Xavfsiz foydalanish — o‘ylab qaror qilish va yordam so‘rashni bilishdir.',
      'Notanish odam “Parolingni yubor, sovrin olasan” dedi.\n1. Parolni yubormang.\n2. Xabarni ishonchli kattaga ko‘rsating.\n3. Xizmatning o‘z sahifasidan tekshiring, shubhali havoladan kirmang.',
      [
        tf(
          'Parolni notanish odamga yuborish mumkin.',
          false,
          'Parol hisob egasining maxfiy ma’lumoti.',
        ),
        mc(
          'Kuchli parolning muhim xususiyati?',
          ['Uzun va noyob', 'Faqat ism', '123456', 'Tug‘ilgan sana'],
          'Uzun va noyob',
          'Uzunlik va noyoblik taxmin qilishni qiyinlashtiradi.',
        ),
        txt(
          'Umumiy qurilmada ish tugagach hisobdan nima qilish kerak? Bir so‘z yozing.',
          'chiqish',
          'Hisobdan chiqish keyingi foydalanuvchining hisobingizga kirishini cheklaydi.',
        ),
        mc(
          'Noqulay xabar kelganda kimdan yordam so‘rash mumkin?',
          [
            'Ishonchli katta yoki o‘qituvchi',
            'Parol so‘ragan begona',
            'Har qanday notanish hisob',
            'Hech kim',
          ],
          'Ishonchli katta yoki o‘qituvchi',
          'Ishonchli kattalar yordam beradi.',
        ),
        tf(
          'Bir xil parolni barcha xizmatlarda ishlatish xavfsizlikni oshiradi.',
          false,
          'Bir xizmatda parol oshkor bo‘lsa, boshqa hisoblar ham xavfga tushadi.',
        ),
        mc(
          'Shaxsiy manzilni ulashishdan oldin nima qilish kerak?',
          [
            'Ishonchli katta bilan maslahatlashish',
            'Darhol yuborish',
            'Ommaga tarqatish',
            'Parolni ham qo‘shish',
          ],
          'Ishonchli katta bilan maslahatlashish',
          'Shaxsiy ma’lumotni ulashish oqibatini avval tushunish kerak.',
        ),
      ],
    ),
  ],
  6: [
    lesson(
      'Matnni formatlash va sarlavha',
      'Hujjat yaratish',
      'Matn mazmunini o‘zgartirmasdan ko‘rinishini yaxshilang.',
      'Matnni tahrir qilish uning mazmunini o‘zgartiradi: xato so‘zni tuzatish yoki gap qo‘shish. Formatlash esa ko‘rinishini o‘zgartiradi: shrift, o‘lcham, qalin yoki kursiv yozuv, tekislash.\n\nSarlavha asosiy matndan ajralib tursin. Bir xil darajadagi sarlavhalarni bir xil uslubda yozish hujjatni tushunarli qiladi. Juda ko‘p turli rang yoki shrift mazmunni o‘qishni qiyinlashtirishi mumkin.\n\nAmal bajarishdan oldin kerakli matnni tanlang. Ro‘yxat uchun dastur ro‘yxat vositasini ishlating; qo‘lda ko‘plab bo‘shliq kiritish sahifa o‘lchami o‘zgarganda buzilishi mumkin. Yakunda hujjatning o‘qilishini tekshiring va saqlang.',
      '“Kasrlar” nomli hujjat:\nSarlavha — yirik va qalin.\nTushuntirish — oddiy, o‘qiladigan o‘lcham.\nMisollar — raqamlangan ro‘yxat.\nHamma sarlavhalar bir xil uslubda.',
      [
        mc(
          'Shrift o‘lchamini o‘zgartirish qaysi amal?',
          ['Formatlash', 'Faylni o‘chirish', 'Parol almashtirish', 'Internetga ulanish'],
          'Formatlash',
          'Ko‘rinish o‘zgaradi, mazmun o‘zgarmaydi.',
        ),
        tf(
          'Xato so‘zni to‘g‘rilash tahrir qilishdir.',
          true,
          'Matn mazmuni yoki yozilishi o‘zgaradi.',
        ),
        txt(
          'Matnni o‘zgartirishdan oldin kerakli qismini nima qilish kerak? Bir so‘z yozing.',
          'tanlash',
          'Amal tanlangan matnga qo‘llanadi.',
        ),
        mc(
          'Hujjatni o‘qishni yengillashtiradigan usul?',
          [
            'Bir xil sarlavha uslublari',
            'Har so‘zga boshqa rang',
            'Juda kichik shrift',
            'Tartibsiz bo‘shliqlar',
          ],
          'Bir xil sarlavha uslublari',
          'Bir xil uslub tuzilmani ko‘rsatadi.',
        ),
        mc(
          'Elementlar ro‘yxati uchun qaysi vosita mos?',
          [
            'Raqamlangan yoki belgili ro‘yxat',
            'Tasodifiy bo‘shliqlar',
            'Parol maydoni',
            'Ovoz yozish',
          ],
          'Raqamlangan yoki belgili ro‘yxat',
          'Ro‘yxat vositasi tartibni saqlaydi.',
        ),
        tf(
          'Formatlashdan keyin hujjatni saqlash shart emas.',
          false,
          'O‘zgarishlarni saqlash kerak.',
        ),
      ],
    ),
    lesson(
      'Hujjatdagi jadval va ma’lumot tartibi',
      'Hujjat yaratish',
      'Takrorlanadigan ma’lumotni satr va ustunlarga joylashtiring.',
      'Jadval ma’lumotni satrlar va ustunlarda tartiblaydi. Katak — satr va ustun kesishgan joy. Har bir ustunga aniq sarlavha qo‘yish ma’lumotni tushunishga yordam beradi.\n\nDars jadvalida ustunlar kun yoki dars nomini, satrlar esa dars tartibini ifodalashi mumkin. Bitta satrga bitta takrorlanadigan yozuvni joylashtirish qulay. Masalan: fan, vaqt, xona.\n\nMa’lumot mos ustunda turishini tekshiring. Jadvalni faqat sahifani bezash uchun ishlatish shart emas; taqqoslash yoki tartiblash kerak bo‘lsa foydali. Matn sig‘ishi uchun ustun enini va qatorlar o‘lchamini moslang.',
      'Ustunlar: Fan | Vaqt | Xona.\n1-satr: Matematika | 08:00 | 12.\n2-satr: Ingliz tili | 09:00 | 15.\n3 ustun va 2 ma’lumot satri 6 ta ma’lumot katagiga ega.',
      [
        txt(
          'Satr va ustun kesishgan joy nima deyiladi?',
          'katak',
          'Jadvalning bitta elementi katak deyiladi.',
        ),
        tf(
          'Jadval ustun sarlavhalari ma’lumot ma’nosini tushuntiradi.',
          true,
          'Masalan, Fan yoki Vaqt sarlavhasi.',
        ),
        mc(
          'Fan, vaqt va xona ma’lumotini tartiblash uchun nima qulay?',
          ['Jadval', 'Tasodifiy matn', 'Faqat bitta rasm', 'Bo‘sh fayl'],
          'Jadval',
          'Takrorlanadigan yozuvlar jadvalda taqqoslanadi.',
        ),
        num('3 ustun va 2 ma’lumot satrida nechta katak bor?', 6, '3 × 2 = 6.'),
        mc(
          'Vaqt ustuniga qaysi qiymat mos?',
          ['09:00', 'Matematika', '15-xona', 'Sarlavha'],
          '09:00',
          '09:00 vaqtni bildiradi.',
        ),
        num('4 ustun va 5 satrli jadvalda nechta katak bor?', 20, '4 × 5 = 20.'),
      ],
    ),
    lesson(
      'Algoritm va ketma-ket bajarish',
      'Algoritmik fikrlash',
      'Aniq, tartibli va yakunlanadigan ko‘rsatma tuzing.',
      'Algoritm vazifani bajarish uchun aniq qadamlar ketma-ketligidir. Har bir qadam tushunarli va bajariladigan bo‘lsin. Algoritmni boshqa odam ham ko‘rsatmaga qarab bajara olishi kerak.\n\nKetma-ket algoritmda amallar navbat bilan bajariladi. Tartib o‘zgarsa, natija ham o‘zgarishi mumkin. “Tayyorla” degan noaniq qadam o‘rniga aynan qaysi amal bajarilishini yozing.\n\nAlgoritmni kichik misolda sinash xatoni topishga yordam beradi. Boshlang‘ich qiymatni yozing va har qadamdan keyin nima o‘zgarganini kuzating. Kiritish — boshlang‘ich ma’lumot, chiqarish — natija.',
      'Ikki son yig‘indisi algoritmi:\n1. a = 7 va b = 5 ni kiriting.\n2. yig‘indi = a + b ni hisoblang.\n3. 12 natijani chiqaring.\nHar qadamning vazifasi aniq.',
      [
        mc(
          'Algoritmning muhim xususiyati?',
          ['Aniq qadamlar', 'Tasodifiy harakat', 'Cheksiz noaniqlik', 'Faqat rasm'],
          'Aniq qadamlar',
          'Qadamlar tushunarli bo‘lishi kerak.',
        ),
        tf(
          'Ketma-ket algoritmda tartib natijaga ta’sir qilishi mumkin.',
          true,
          'Amallar navbat bilan bajariladi.',
        ),
        num('a = 7, b = 5. yig‘indi = a + b natijasi?', 12, '7 + 5 = 12.'),
        txt(
          'Algoritmning yakuniy natijasini foydalanuvchiga berish amali: kiritish yoki chiqarish?',
          'chiqarish',
          'Chiqarish natijani ko‘rsatadi.',
        ),
        num(
          'x = 2. Avval x ga 3 qo‘shing, keyin 4 ga ko‘paytiring. Natija?',
          20,
          '(2 + 3) × 4 = 20.',
        ),
        num(
          'x = 2. Avval x ni 4 ga ko‘paytiring, keyin 3 qo‘shing. Natija?',
          11,
          '2 × 4 + 3 = 11; tartib o‘zgardi.',
        ),
      ],
    ),
    lesson(
      'Blokli dasturlash: harakat va takrorlash',
      'Dasturlashga qadam',
      'Bloklarning tartibi va takrorlash soniga qarab natija toping.',
      'Blokli dasturlashda buyruqlar tayyor bloklar bilan tuziladi. Scratch kabi muhitda sahnadagi qahramon sprite deb ataladi. Qahramon yurishi, burilishi va xabar ko‘rsatishi mumkin.\n\nHarakat bloklari tartib bilan bajariladi. Takrorlash bloki bir nechta bir xil buyruqni ixcham yozishga yordam beradi. “4 marta takrorla: 10 qadam yur” jami 40 qadam harakatni bildiradi.\n\nDastur boshlanishi hodisa bilan bog‘lanishi mumkin, masalan boshlash belgisi bosilishi. Harakatni tushunishda qahramonning dastlabki joyi va yo‘nalishini hisobga oling. Bu darsda faqat bir yo‘nalishdagi qadamlar yig‘indisini hisoblaymiz.',
      'Qahramon boshlang‘ich joyda.\n3 marta takrorla: 8 qadam yur.\nJami 3 × 8 = 24 qadam.\nKeyin yana 6 qadam yur: jami 30 qadam.',
      [
        txt(
          'Scratch sahnasidagi qahramonning inglizcha nomi?',
          'sprite',
          'Qahramon sprite deb ataladi.',
        ),
        tf(
          'Takrorlash bloki bir xil buyruqlarni bir necha marta bajaradi.',
          true,
          'Masalan, repeat 4 times.',
        ),
        num('4 marta 10 qadam yurilsa, jami necha qadam?', 40, '4 × 10 = 40.'),
        mc(
          'Dastur boshlash belgisi bosilganda ishga tushsa, bu nimaga misol?',
          ['Hodisaga', 'Papka nomiga', 'Fayl kengaytmasiga', 'Matn shriftiga'],
          'Hodisaga',
          'Bosish hodisasi bloklar bajarilishini boshlaydi.',
        ),
        num('3 marta 8 qadam va keyin 6 qadam: jami qancha?', 30, '3 × 8 + 6 = 30.'),
        num('5 marta 12 qadam yurilsa, jami necha qadam?', 60, '5 × 12 = 60.'),
      ],
    ),
    lesson(
      'Internetda qidirish va manbani tekshirish',
      'Internet savodxonligi',
      'Qidiruv so‘rovini aniq tuzing va natija manbasini baholang.',
      'Qidiruv tizimi kerakli sahifalarni topishga yordam beradi. Aniq so‘rov foydali natijaga olib keladi: “6-sinf kasrlarni ko‘paytirish misollari” umumiy “matematika” so‘rovidan aniqroq.\n\nNatijaning birinchi o‘rinda chiqishi uning albatta to‘g‘riligini isbotlamaydi. Sahifa muallifi, tashkilot, sana va keltirilgan dalillarni ko‘ring. O‘quv ma’lumoti uchun ishonchli ta’lim manbalarini tekshirish foydali.\n\nBir-biriga zid xabarlar bo‘lsa, bir nechta mustaqil manbani taqqoslang. Qidiruvdagi reklama natijasi bilan oddiy natijani farqlang. Shubhali sahifada shaxsiy ma’lumot yoki parol kiritmang.',
      'Vazifa: uchburchak ichki burchaklari yig‘indisini tekshirish.\nAniq so‘rov yozing. Ta’lim manbasini oching.\nMuallif va dalilni tekshiring. Boshqa mustaqil manba bilan solishtiring.',
      [
        mc(
          'Qaysi qidiruv so‘rovi aniqroq?',
          ['6-sinf kasrlarni ko‘paytirish misollari', 'narsa', 'internet', 'hammasi'],
          '6-sinf kasrlarni ko‘paytirish misollari',
          'Sinf, mavzu va maqsad ko‘rsatilgan.',
        ),
        tf(
          'Birinchi natija har doim to‘g‘ri bo‘ladi.',
          false,
          'O‘rin manba ishonchliligini kafolatlamaydi.',
        ),
        txt(
          'Sahifada xabar qachon yozilganini bilish uchun nimani tekshiramiz? Bir so‘z yozing.',
          'sana|sanasini',
          'Sana ma’lumotning qachon yozilganini ko‘rsatadi.',
        ),
        mc(
          'Manbani baholash uchun qaysi ma’lumot muhim?',
          [
            'Muallif va dalillar',
            'Faqat chiroyli rang',
            'Faqat katta sarlavha',
            'Faqat ko‘rishlar soni',
          ],
          'Muallif va dalillar',
          'Kim yozgani va nima bilan asoslagani muhim.',
        ),
        mc(
          'Ikki sahifa turlicha javob bersa, nima qilasiz?',
          [
            'Mustaqil manbalar va dalillarni taqqoslayman',
            'Tasodifiy bittasini tanlayman',
            'Faqat reklamaga ishonaman',
            'Parolimni yuboraman',
          ],
          'Mustaqil manbalar va dalillarni taqqoslayman',
          'Dalillarni solishtirish asosli xulosa beradi.',
        ),
        tf(
          'Reklama natijasini oddiy qidiruv natijasidan farqlash kerak.',
          true,
          'Reklama belgisini va manbani tekshiring.',
        ),
      ],
    ),
    lesson(
      'Taqdimot: slayd va asosiy fikr',
      'G‘oyani tushuntirish',
      'Taqdimotda maqsad, ketma-ketlik va o‘qilishni saqlang.',
      'Taqdimot fikrni slaydlar orqali tushuntiradi. Har bir slayd bitta asosiy fikrni qo‘llab-quvvatlasa, tinglovchi kuzatishi oson bo‘ladi. Sarlavha slayd nima haqida ekanini ko‘rsatsin.\n\nBoshlanishda mavzu va maqsad, o‘rtada asosiy tushuntirish yoki dalil, oxirida xulosa beriladi. Juda ko‘p matnni bitta slaydga joylashtirish o‘qishni qiyinlashtiradi. Matn va fon yetarli farqlansin.\n\nRasm yoki diagramma mazmunni tushuntirishga xizmat qilsin. Tashqi manbadan olingan rasm yoki ma’lumotning manbasini ko‘rsating. Taqdimotni namoyish qilishdan oldin matn, tartib va o‘qilishini tekshiring.',
      '“Suvni tejash” taqdimoti:\n1. Mavzu va maqsad.\n2. Uyda suv sarfi misoli.\n3. Amalga oshirish mumkin bo‘lgan odatlar.\n4. Xulosa va foydalanilgan manbalar.',
      [
        mc(
          'Bitta slaydda odatda nimaga e’tibor berish qulay?',
          ['Bitta asosiy fikrga', 'Yuzlab tasodifiy gapga', 'Faqat bezakka', 'Faqat ovozga'],
          'Bitta asosiy fikrga',
          'Asosiy fikr aniq bo‘lsa tushunish oson.',
        ),
        tf(
          'Kichik matn va past rang farqi o‘qishni qiyinlashtiradi.',
          true,
          'Matn o‘qiladigan bo‘lishi kerak.',
        ),
        txt(
          'Taqdimotning yakuniy asosiy qismi nima? “Xulosa” yoki “kirish”.',
          'xulosa',
          'Yakuniy qismda asosiy natija umumlashtiriladi.',
        ),
        mc(
          'Taqdimot ketma-ketligini tanlang.',
          [
            'Kirish → tushuntirish → xulosa',
            'Xulosa → tasodifiy matn → mavzu',
            'Faqat reklama',
            'Faqat rasmlar',
          ],
          'Kirish → tushuntirish → xulosa',
          'Maqsad, asosiy ma’lumot va natija tartibli beriladi.',
        ),
        tf(
          'Tashqi manbadan olingan ma’lumotning manbasini ko‘rsatish kerak.',
          true,
          'Manba mualliflik va tekshirish uchun muhim.',
        ),
        num(
          'Kirishga 1, asosiy qismga 3 va xulosaga 1 slayd ajratsak, jami nechta slayd?',
          5,
          '1 + 3 + 1 = 5.',
        ),
      ],
    ),
  ],
  7: [
    lesson(
      'Ikkilik sanoq sistemasiga o‘tish',
      'Axborotni kodlash',
      'Ikkilik yozuvni xona qiymatlari orqali o‘nlik songa aylantiring.',
      'Ikkilik sanoq sistemasida faqat 0 va 1 raqamlari ishlatiladi. O‘ngdan chapga xona qiymatlari 1, 2, 4, 8, 16 kabi ikkiga ko‘payib boradi.\n\n1011₂ sonida 8, 2 va 1 qiymatli xonalarda 1 bor. Yig‘indi 8 + 2 + 1 = 11. 0 turgan xona yig‘indiga hissa qo‘shmaydi.\n\nO‘nlik sonni ikkilikka yozish uchun uni mos 2 darajalari yig‘indisi sifatida ajrating. 13 = 8 + 4 + 1, demak 1101₂. Qo‘shishda 1 + 1 = 10₂: 0 yoziladi va keyingi xonaga 1 o‘tadi. Qaysi sanoq sistemasida javob so‘ralganini tekshiring.',
      '13 ni ikkilikka aylantiramiz.\nXonalar: 8 | 4 | 2 | 1.\n13 = 8 + 4 + 0 + 1.\nRaqamlar: 1 | 1 | 0 | 1 → 1101₂.',
      [
        num('1011₂ soni o‘nlikda nechaga teng?', 11, '8 + 0 + 2 + 1 = 11.'),
        tf('Ikkilik sistemada faqat 0 va 1 ishlatiladi.', true, 'Asos 2, raqamlar 0 va 1.'),
        txt(
          '13 ni ikkilikda yozing. Faqat 0 va 1 raqamlarini kiriting.',
          '1101',
          '13 = 8 + 4 + 1, demak 1101₂.',
        ),
        txt('Ikkilikda 1 + 1 natijasini yozing.', '10', '2 o‘nlikda, 10 ikkilikda.'),
        txt('1010₂ + 101₂ natijasini ikkilikda yozing.', '1111', '10 + 5 = 15; 15 ikkilikda 1111.'),
        num('10000₂ soni o‘nlikda nechaga teng?', 16, '1 × 16 va qolgan xonalarda 0.'),
      ],
    ),
    lesson(
      'Axborot hajmi: bit, bayt va KiB',
      'Axborot o‘lchovi',
      'Bit va baytni farqlang, ikkilik prefiksni to‘g‘ri ishlating.',
      'Bit ikkilik raqamni ifodalaydi. Bir bayt 8 bitdan iborat. Shuning uchun baytdan bitga o‘tishda 8 ga ko‘paytiramiz, bitdan baytga o‘tishda 8 ga bo‘lamiz.\n\nKiB (kibibayt) ikkilik prefiks bo‘lib, 1 KiB = 1 024 bayt. kB esa o‘nlik prefiksda 1 000 bayt. Bu ikki belgini aralashtirmaslik kerak.\n\nSavolda birlikni diqqat bilan o‘qing. 16 bayt = 128 bit. 2 KiB = 2 048 bayt. Hisoblashda avval bir xil birlikka o‘ting.',
      '2 KiB ni bitga o‘tkazamiz:\n2 × 1 024 = 2 048 bayt.\n2 048 × 8 = 16 384 bit.\nKiB va kB bir xil belgi emas.',
      [
        num('1 bayt necha bit?', 8, 'Bir bayt 8 bitdan iborat.'),
        tf('1 KiB va 1 kB aynan bir xil miqdor.', false, 'KiB = 1 024 bayt; kB = 1 000 bayt.'),
        num('16 bayt necha bit?', 128, '16 × 8 = 128 bit.'),
        mc(
          '1 KiB nechta bayt?',
          ['1 024', '1 000', '8', '128'],
          '1 024',
          'Ki — ikkilik prefiks, 2¹⁰ = 1 024.',
        ),
        num('2 KiB necha bayt?', 2048, '2 × 1 024 = 2 048.'),
        num('2 KiB necha bit?', 16384, '2 × 1 024 × 8 = 16 384.'),
      ],
    ),
    lesson(
      'Elektron jadval kataklari va formulalar',
      'Elektron jadvallar',
      'Katak manzili, formula va yig‘indi hisobini tushuning.',
      'Elektron jadvalda ustunlar harflar, satrlar raqamlar bilan belgilanadi. A1 — A ustuni va 1-satri kesishgan katak. Kataklarda son, matn yoki formula bo‘lishi mumkin.\n\nFormula odatda = belgisi bilan boshlanadi. =A1+A2 ikki katak qiymatini qo‘shadi. Katakdagi qiymat o‘zgarsa, unga murojaat qiluvchi formula natijasi ham qayta hisoblanadi.\n\nBu darsda funksiyalarning inglizcha nomlarini ishlatamiz. SUM(A1:A3) A1 dan A3 gacha bo‘lgan oraliqni qo‘shadi. A1:A3 — uchta katak. Formulada tayyor son o‘rniga katak manzilidan foydalanish jadvalni qayta ishlatishga yordam beradi.',
      'A1 = 12, A2 = 8, A3 = 5.\n=A1+A2 → 20.\n=SUM(A1:A3) → 25.\nA2 10 ga o‘zgarsa, birinchi formula 22 bo‘ladi.',
      [
        mc(
          'A1 manzili nimani bildiradi?',
          ['A ustuni, 1-satr', '1-ustun, A-satr', 'Faqat fayl nomi', 'Faqat formula nomi'],
          'A ustuni, 1-satr',
          'Harflar ustunni, raqamlar satrni bildiradi.',
        ),
        tf('Formula odatda = bilan boshlanadi.', true, 'Masalan, =A1+A2.'),
        num('A1 = 12, A2 = 8. =A1+A2 natijasi?', 20, '12 + 8 = 20.'),
        txt(
          'Inglizcha nomlarda oraliq qiymatlarini qo‘shadigan funksiya nomi?',
          'sum',
          'SUM yig‘indini hisoblaydi.',
        ),
        num('A1 = 12, A2 = 8, A3 = 5. =SUM(A1:A3) natijasi?', 25, '12 + 8 + 5 = 25.'),
        num(
          'A1 = 12, A2 = 10. =A1+A2 natijasi?',
          22,
          '12 + 10 = 22, formula qiymatlar bilan qayta hisoblanadi.',
        ),
      ],
    ),
    lesson(
      'Shartli algoritm: agar — aks holda',
      'Algoritm tuzilmalari',
      'Shartning rost yoki yolg‘onligiga qarab bajariladigan yo‘lni tanlang.',
      'Shartli algoritmda shart tekshiriladi. Rost bo‘lsa bir yo‘l, yolg‘on bo‘lsa boshqa yo‘l bajariladi. Psevdokodda: agar shart bo‘lsa ... aks holda ... shaklidan foydalanamiz.\n\nTaqqoslash belgilarini farqlang: > katta, < kichik, >= katta yoki teng, <= kichik yoki teng. Chegaradagi qiymatni sinash xatoni topadi. Masalan, ball >= 60 shartida aynan 60 ham rost.\n\nBoshlang‘ich qiymatni shartga qo‘ying, qaysi yo‘l tanlanganini yozing va faqat shu yo‘ldagi amalni bajaring. Ikkala yo‘lni bir vaqtda bajarish oddiy agar—aks holda tuzilmasiga mos emas.',
      'x = 10. Agar x > 10 bo‘lsa, x + 1; aks holda x − 1.\n10 > 10 yolg‘on, shuning uchun ikkinchi yo‘l: 10 − 1 = 9.',
      [
        mc(
          'ball >= 60 shartida ball = 60 bo‘lsa, shart qanday?',
          ['Rost', 'Yolg‘on', 'Har doim xato', 'Qiymat yo‘q'],
          'Rost',
          '>= tenglikni ham o‘z ichiga oladi.',
        ),
        tf(
          '> va >= bir xil shartni bildiradi.',
          false,
          '>= tenglikni qabul qiladi; > esa qabul qilmaydi.',
        ),
        num(
          'x = 7. Agar x >= 5 bo‘lsa 2x, aks holda x + 1. Natija?',
          14,
          '7 >= 5 rost; 2 × 7 = 14.',
        ),
        txt(
          'Agar—aks holda tuzilmasi algoritmning qaysi turiga tegishli? Bir so‘z yozing.',
          'shartli',
          'Bu shartli algoritm.',
        ),
        num(
          'x = 10. Agar x > 10 bo‘lsa x + 1, aks holda x − 1. Natija?',
          9,
          'Shart yolg‘on, 10 − 1 = 9.',
        ),
        num(
          'x = −4. Agar x < 0 bo‘lsa −x, aks holda x. Natija?',
          4,
          '−4 < 0 rost, demak −(−4) = 4.',
        ),
      ],
    ),
    lesson(
      'Takrorlash va o‘zgaruvchi qiymati',
      'Algoritm tuzilmalari',
      'Siklning har bir qadamida o‘zgaruvchi qanday o‘zgarishini kuzating.',
      'Takrorlash yoki sikl bir xil amallarni bir necha marta bajaradi. O‘zgaruvchi qiymati har qadamdan keyin yangilanishi mumkin. x = x + 3 eski qiymatga 3 qo‘shib, natijani x ga saqlashni bildiradi.\n\nBoshlang‘ich x = 0 bo‘lsa, bu amal to‘rt marta bajarilganda qiymatlar 3, 6, 9, 12 bo‘ladi. Natija 12. Boshlang‘ich qiymatni va takrorlash sonini unutish xatoga olib keladi.\n\nSikl jadvali yordam beradi: qadam raqami va x ning yangi qiymatini alohida yozing. Faqat yakuniy qiymat emas, oraliq qiymatlar ham algoritmni tushunishga xizmat qiladi. Sikl tugagandan keyingi qo‘shimcha amal alohida bajariladi.',
      'x = 1; 3 marta takrorla: x = x × 2.\n1-qadam: 2; 2-qadam: 4; 3-qadam: 8.\nKeyin x = x + 5 bo‘lsa, yakuniy qiymat 13.',
      [
        num('x = 0; x = x + 3 amali 4 marta bajariladi. Yakuniy x?', 12, '0 → 3 → 6 → 9 → 12.'),
        tf(
          'Sikl natijasini topishda boshlang‘ich qiymat muhim.',
          true,
          'Har qadam oldingi qiymatga bog‘liq.',
        ),
        num('x = 1; x = x × 2 amali 3 marta bajariladi. Yakuniy x?', 8, '1 → 2 → 4 → 8.'),
        txt(
          'Bir xil amalni takrorlaydigan tuzilma: sikl yoki papka?',
          'sikl',
          'Takrorlash tuzilmasi sikl deyiladi.',
        ),
        num('x = 5; 3 marta x = x + 2. Yakuniy x?', 11, '5 + 3 × 2 = 11.'),
        num(
          'x = 1; 3 marta x = x × 2; keyin x = x + 5. Natija?',
          13,
          'Sikldan keyin 8; keyin 8 + 5 = 13.',
        ),
      ],
    ),
    lesson(
      'Ma’lumotni tekshirish va raqamli iz',
      'Mas’uliyatli internet',
      'Dalil, fikr va shaxsiy ma’lumotni ajrating.',
      'Dalil bilan tekshirish mumkin bo‘lgan xabar va shaxsiy fikr bir xil emas. “Uchrashuv soat 14:00 da” jadval bilan tekshiriladi. “Bu eng qiziqarli mavzu” esa shaxsiy baho bo‘lishi mumkin.\n\nXabarni ulashishdan oldin asl manba, muallif, sana va dalillarni tekshiring. Juda keskin sarlavha yoki ko‘p ulashilgan xabar rostlikni kafolatlamaydi. Bir-biridan nusxa ko‘chirgan sahifalar mustaqil tasdiq hisoblanmaydi.\n\nRaqamli iz internetdagi faoliyatdan qoladigan ma’lumotdir. Begona odamning shaxsiy ma’lumotini ruxsatsiz ulashmang. O‘zingiz haqingizdagi ma’lumot ommaga chiqsa, kim ko‘rishini va keyin o‘chirish qanchalik qiyin bo‘lishini o‘ylang.',
      'Xabar: “Ertaga maktab darsi bo‘lmaydi”.\n1. Rasmiy maktab e’lonini tekshiring.\n2. Sana va kim yuborganini tekshiring.\n3. Eski yoki asossiz xabarni darhol tarqatmang.',
      [
        mc(
          'Qaysi gap shaxsiy fikrga misol?',
          [
            'Bu eng qiziqarli mavzu.',
            'Uchrashuv 14:00 da.',
            'Sinfda 6 ta stol bor.',
            'Fayl hajmi 12 bayt.',
          ],
          'Bu eng qiziqarli mavzu.',
          'Qiziqarlilik shaxsiy bahoga bog‘liq.',
        ),
        tf(
          'Ko‘p ulashilgan xabar albatta rost.',
          false,
          'Ulashishlar soni dalil o‘rnini bosmaydi.',
        ),
        txt(
          'Xabar qachon yozilganini bilish uchun nimani tekshiramiz? Bir so‘z.',
          'sana|sanasini',
          'Sana eski xabarni yangi voqeadan ajratishga yordam beradi.',
        ),
        mc(
          'Mustaqil tasdiq uchun qaysi holat yaxshiroq?',
          [
            'Alohida dalil keltirgan boshqa manba',
            'Asl xabarni aynan nusxalagan sahifa',
            'Faqat katta sarlavha',
            'Faqat anonim izoh',
          ],
          'Alohida dalil keltirgan boshqa manba',
          'Mustaqil dalil bir xabarning nusxasi bo‘lmasligi kerak.',
        ),
        tf(
          'Begona odamning shaxsiy ma’lumotini ruxsatsiz ulashish to‘g‘ri.',
          false,
          'Shaxsiy ma’lumotni hurmat qilish kerak.',
        ),
        mc(
          '“Ertaga dars bo‘lmaydi” xabarini tekshirish uchun birinchi qadam?',
          [
            'Rasmiy maktab e’loni va sanani tekshirish',
            'Darhol hammaga yuborish',
            'Anonim izohni tanlash',
            'Parolni jo‘natish',
          ],
          'Rasmiy maktab e’loni va sanani tekshirish',
          'Mas’ul tashkilot e’loni va sana tekshiriladi.',
        ),
      ],
    ),
  ],
};
