import { lesson, mc, tf, num, txt, type GradeCurriculum } from './types';

export const mathematics: GradeCurriculum = {
  5: [
    lesson(
      'Natural sonlar va xona qiymati',
      'Sonlar olami',
      'Natural sonni xona birliklariga ajrating va sonlarni taqqoslang.',
      'Son yozuvidagi raqamning qiymati uning o‘rniga bog‘liq. O‘ngdan boshlab birlik, o‘nlik, yuzlik va minglik xonalari keladi. 3 482 = 3 000 + 400 + 80 + 2. Shu sababli bir xil 4 raqami 42 da 40 ni, 402 da 400 ni bildiradi.\n\nSonlarni taqqoslashda avval raqamlar soniga qaraymiz. Raqamlar soni teng bo‘lsa, eng chap xonadan boshlab birinchi farqli raqamni taqqoslaymiz. 6 210 soni 6 120 dan katta: mingliklar teng, lekin yuzlikdagi 2 soni 1 dan katta.\n\nQo‘shishda bir xil xonalarni bir-birining ostiga yozing. Birliklar yig‘indisi 10 yoki undan katta bo‘lsa, bir o‘nlik keyingi xonaga o‘tadi. Taxminiy hisob natijani tekshirishga yordam beradi: 945 + 378 taxminan 900 + 400 = 1 300.',
      '4 325 ni yoyamiz: 4 minglik + 3 yuzlik + 2 o‘nlik + 5 birlik.\n945 + 378: birliklar 5 + 8 = 13; 3 ni yozib, 1 o‘nlikni o‘tkazamiz. Yakuniy natija 1 323.',
      [
        mc(
          '4 926 sonidagi 9 raqamining qiymati qancha?',
          ['9', '90', '900', '9 000'],
          '900',
          '9 yuzlik xonasida turibdi, shuning uchun qiymati 900.',
        ),
        tf(
          '10 000 soni 9 999 dan katta.',
          true,
          'Besh xonali 10 000 to‘rt xonali 9 999 dan katta.',
        ),
        num(
          '4 minglik, 3 yuzlik, 2 o‘nlik va 5 birlikdan tuzilgan sonni yozing.',
          4325,
          '4 000 + 300 + 20 + 5 = 4 325.',
        ),
        txt(
          '456 sonidagi 4 qaysi xonada? Xona nomini yozing.',
          'yuzlik|yuzliklar|yuzlar',
          '4 raqami yuzlik xonasida: qiymati 400.',
        ),
        num(
          'Kutubxonada 945 kitob bor edi, yana 378 ta keldi. Jami nechta kitob bo‘ldi?',
          1323,
          '945 + 378 = 1 323.',
          'Sonlarni xonalari bo‘yicha qo‘shing.',
        ),
        mc(
          'Eng katta sonni tanlang.',
          ['6 021', '6 210', '6 120', '6 201'],
          '6 210',
          'Mingliklar teng. Yuzlikdagi 2 eng katta; 6 210 va 6 201 dan o‘nlikdagi 1 kattaroq.',
        ),
      ],
    ),
    lesson(
      'Amallar tartibi va qavslar',
      'Hisoblash strategiyasi',
      'Bir nechta amalli ifodani to‘g‘ri tartibda hisoblang.',
      'Ifodada qavs bo‘lsa, avval qavs ichidagi amal bajariladi. Keyin ko‘paytirish va bo‘lish, oxirida qo‘shish va ayirish bajariladi. Bir xil ustuvorlikdagi amallar chapdan o‘ngga hisoblanadi.\n\n6 + 4 × 3 ifodasida avval 4 × 3 = 12, keyin 6 + 12 = 18. (6 + 4) × 3 esa 10 × 3 = 30. Qavslar natijani o‘zgartirdi, chunki ular qaysi amal birinchi bajarilishini ko‘rsatadi.\n\n48 ÷ 6 × 2 da bo‘lish va ko‘paytirish teng ustuvorlikka ega. Chapdan o‘ngga: 48 ÷ 6 = 8, 8 × 2 = 16. Har bir bosqichda ifodaning hisoblangan qismini uning qiymati bilan almashtiring.',
      '18 − 2 × (3 + 4)\n1. Qavs: 3 + 4 = 7.\n2. Ko‘paytirish: 2 × 7 = 14.\n3. Ayirish: 18 − 14 = 4.',
      [
        num('6 + 4 × 3 ni hisoblang.', 18, 'Avval 4 × 3 = 12; keyin 6 + 12 = 18.'),
        mc(
          '(6 + 4) × 3 nechaga teng?',
          ['18', '30', '24', '22'],
          '30',
          'Qavs ichida 6 + 4 = 10; 10 × 3 = 30.',
        ),
        tf(
          'Ko‘paytirish va bo‘lish bir xil ustuvorlikka ega.',
          true,
          'Ular bir xil ustuvorlikka ega va chapdan o‘ngga bajariladi.',
        ),
        num('48 ÷ 6 × 2 ni hisoblang.', 16, 'Chapdan o‘ngga: 48 ÷ 6 = 8; 8 × 2 = 16.'),
        num('28 − 12 ÷ 3 ni hisoblang.', 24, 'Avval 12 ÷ 3 = 4; keyin 28 − 4 = 24.'),
        num(
          '4 × (7 + 5) − 9 nechaga teng?',
          39,
          '7 + 5 = 12; 4 × 12 = 48; 48 − 9 = 39.',
          'Qavs → ko‘paytirish → ayirish tartibida ishlang.',
        ),
      ],
    ),
    lesson(
      'Kasrni tushunish va qisqartirish',
      'Oddiy kasrlar',
      'Surat va maxrajni farqlang, teng kasrlarni toping.',
      'Butun narsa teng qismlarga bo‘linganda oddiy kasr hosil bo‘ladi. Maxraj butun nechta teng qismga bo‘linganini, surat esa nechta qism olinganini bildiradi. 3/8 da maxraj 8, surat 3.\n\nSurat va maxrajni bir xil noldan farqli songa bo‘lish kasrning qiymatini o‘zgartirmaydi. Masalan, 2/6 ning ikkala qismini 2 ga bo‘lsak, 1/3 hosil bo‘ladi. Bu qisqartirish deyiladi.\n\nKasrlarni taqqoslash uchun umumiy maxrajdan foydalanish mumkin. 3/4 = 9/12, 2/3 = 8/12. Shu sababli 3/4 kattaroq. Sonning bir qismini topishda sonni maxrajga bo‘lib, suratga ko‘paytiramiz.',
      '20 dona qalamning 4/5 qismini topamiz: 20 ÷ 5 = 4; 4 × 4 = 16.\nTekshirish: beshdan bir qism 4 ta qalam; to‘rtta shunday qism 16 ta.',
      [
        mc(
          '3/8 kasrining surati qaysi?',
          ['3', '8', '11', '5'],
          '3',
          'Kasr chizig‘i ustidagi 3 — surat.',
        ),
        tf('1/3 + 1/3 = 2/3.', true, 'Bir xil maxraj saqlanadi, suratlar qo‘shiladi.'),
        num('Pitsa 8 teng bo‘lak edi. 3 bo‘lagi yeyildi. Nechta bo‘lak qoldi?', 5, '8 − 3 = 5.'),
        txt(
          '2/6 ni qisqartiring. Javobni a/b shaklida yozing.',
          '1/3',
          'Surat va maxrajni 2 ga bo‘lamiz: 2/6 = 1/3.',
        ),
        num('20 ning 4/5 qismini toping.', 16, '20 ÷ 5 × 4 = 16.'),
        mc(
          'Qaysi kasr katta?',
          ['2/3', '3/4', 'Ikkalasi teng', 'Taqqoslab bo‘lmaydi'],
          '3/4',
          'Umumiy maxraj 12: 2/3 = 8/12, 3/4 = 9/12.',
        ),
      ],
    ),
    lesson(
      'O‘nli kasrlarni qo‘shish va ayirish',
      'O‘nli kasrlar',
      'O‘nli kasrlarni xona qiymatlari bo‘yicha hisoblang.',
      'O‘nli kasrda butun va kasr qismlar vergul bilan ajraladi. Verguldan keyingi birinchi raqam o‘ndan bir, ikkinchisi yuzdan bir ulushni bildiradi. 0,75 = 75/100.\n\nQo‘shish va ayirishda vergullarni bir-birining ostiga qo‘ying. Kasr qismidagi raqamlar sonini tenglashtirish uchun oxiriga nol qo‘shish mumkin: 3,4 = 3,40. Bu qiymatni o‘zgartirmaydi.\n\n3,40 + 1,25 = 4,65. Ayirishda ham bir xil xonalar mos keladi: 7,08 − 2,60 = 4,48. Pul yoki uzunlik masalalarida javobning birligini ham tekshiring. Sonli javob maydonida vergul yoki nuqta ishlatishingiz mumkin.',
      '10 so‘mdan 2,35 va 3,60 so‘mlik xarajatni ayiramiz.\nJami xarajat: 2,35 + 3,60 = 5,95.\nQolgan summa: 10,00 − 5,95 = 4,05.',
      [
        num('3,4 + 1,25 ni hisoblang.', 4.65, '3,40 + 1,25 = 4,65.'),
        tf('2,5 + 0,4 = 2,9.', true, 'O‘ndan bir ulushlar: 5 + 4 = 9.'),
        mc(
          '0,75 qaysi kasrga teng?',
          ['75/10', '75/100', '7/5', '3/5'],
          '75/100',
          'Verguldan keyin ikki xona bor: 75 yuzdan bir ulush.',
        ),
        num('7,08 − 2,6 ni hisoblang.', 4.48, '7,08 − 2,60 = 4,48.'),
        num('2,35 + 3,60 nechaga teng?', 5.95, '2,35 + 3,60 = 5,95.'),
        num(
          '10 − 2,35 − 3,60 ni hisoblang.',
          4.05,
          'Avval xarajatlarni qo‘shamiz: 5,95. 10 − 5,95 = 4,05.',
        ),
      ],
    ),
    lesson(
      'Uzunlik, massa va hajm birliklari',
      'O‘lchash',
      'O‘lchov birliklarini almashtiring va bir xil birlikda hisoblang.',
      'Bir miqdor turli birliklarda yozilishi mumkin. 1 m = 100 cm, 1 km = 1 000 m. Massa uchun 1 kg = 1 000 g, sig‘im uchun 1 l = 1 000 ml.\n\nKatta birlikdan kichik birlikka o‘tganda mos songa ko‘paytiramiz. 2,5 m = 2,5 × 100 = 250 cm. Kichik birlikdan katta birlikka o‘tganda bo‘lamiz: 3 000 g = 3 000 ÷ 1 000 = 3 kg.\n\nBir nechta birlikdagi miqdorlarni qo‘shishdan oldin ularni bir xil birlikka keltiring. 3 m 20 cm = 300 cm + 20 cm = 320 cm. Yuz uzunlik emas: u kvadrat birlikda, masalan m² da o‘lchanadi.',
      '5 l 250 ml ni millilitrga aylantiramiz.\n5 l = 5 × 1 000 = 5 000 ml.\n5 000 ml + 250 ml = 5 250 ml.',
      [
        num('2,5 metr necha santimetr?', 250, '2,5 × 100 = 250 cm.'),
        num('3 000 gramm necha kilogramm?', 3, '3 000 ÷ 1 000 = 3 kg.'),
        tf('1 litr 100 millilitrga teng.', false, '1 litr = 1 000 millilitr.'),
        mc(
          'Yuzaning o‘lchov birligini tanlang.',
          ['m', 'm²', 'kg', 'l'],
          'm²',
          'Yuza kvadrat birliklarda o‘lchanadi.',
        ),
        num('3 m 20 cm necha santimetr?', 320, '300 + 20 = 320 cm.'),
        num('5 l 250 ml necha millilitr?', 5250, '5 000 + 250 = 5 250 ml.'),
      ],
    ),
    lesson(
      'Perimetr va yuzani farqlash',
      'Geometriya asoslari',
      'To‘rtburchakning chegarasi va ichki maydonini alohida hisoblang.',
      'Perimetr — shaklning barcha tomonlari uzunliklari yig‘indisi. To‘g‘ri to‘rtburchakda qarama-qarshi tomonlar teng: P = 2 × (a + b). Yuz esa shakl ichki maydonini bildiradi: S = a × b.\n\nPerimetr cm yoki m da, yuz cm² yoki m² da o‘lchanadi. 8 m va 3 m tomonli xonaning yuzi 24 m², perimetri esa 22 m. Ikkala natija bir xil miqdor emas.\n\nKvadratning barcha tomonlari teng: P = 4a, S = a². Yuza va bitta tomon ma’lum bo‘lsa, ikkinchi tomonni bo‘lish orqali topamiz. Masalan, S = 48 m², b = 6 m bo‘lsa, a = 48 ÷ 6 = 8 m.',
      'Xona 10 m × 4 m.\nPolning yuzi: 10 × 4 = 40 m².\nDevorlar bo‘ylab umumiy uzunlik: 2 × (10 + 4) = 28 m.\nPolni qoplash uchun yuza kerak, chegara bo‘ylab lenta uchun perimetr kerak.',
      [
        num(
          'Tomonlari 8 m va 3 m bo‘lgan to‘g‘ri to‘rtburchakning yuzi necha m²?',
          24,
          'S = 8 × 3 = 24.',
        ),
        tf(
          'To‘g‘ri to‘rtburchak perimetri 2 × (a + b) bilan topiladi.',
          true,
          'Ikki uzunlik va ikki en bor.',
        ),
        mc(
          'Tomoni 8 bo‘lgan kvadrat perimetri?',
          ['16', '32', '64', '24'],
          '32',
          'P = 4 × 8 = 32.',
        ),
        num(
          'Yuzi 48 m², eni 6 m bo‘lgan to‘g‘ri to‘rtburchakning uzunligi necha metr?',
          8,
          'a = S ÷ b = 48 ÷ 6 = 8.',
        ),
        num(
          '10 m × 4 m polni 1 m² lik qoplamalar bilan yopish uchun nechta qoplama kerak?',
          40,
          'Pol yuzi 40 m²; har biri 1 m² bo‘lsa, 40 ta kerak.',
        ),
        num(
          'Uzunligi 7 m, eni 5 m bo‘lgan to‘g‘ri to‘rtburchakning perimetri necha metr?',
          24,
          'P = 2 × (7 + 5) = 24.',
        ),
      ],
    ),
  ],
  6: [
    lesson(
      'Kasrlarni ko‘paytirish',
      'Kasrlar bilan amallar',
      'Kasrning qismini toping va ko‘paytmani qisqartiring.',
      'Kasrlarni ko‘paytirishda suratlar o‘zaro, maxrajlar o‘zaro ko‘paytiriladi: a/b × c/d = ac/bd. Maxrajlar nol bo‘lmasligi kerak.\n\nKo‘paytirishdan oldin yoki keyin qisqartirish mumkin. 2/3 × 3/4 da suratdagi va maxrajdagi 3 qisqaradi; natija 2/4 = 1/2. Bu hisobni soddalashtiradi.\n\nButun sonni kasr ko‘rinishida yozish mumkin: 20 = 20/1. Shunda 20 ning 3/5 qismi 20/1 × 3/5 = 60/5 = 12. 0 va 1 orasidagi musbat kasrga ko‘paytirish musbat sonning faqat bir qismini olishni bildiradi.',
      '4/7 × 7/8\n1. 7 larni qisqartiramiz.\n2. Qolgan ko‘paytma 4/8.\n3. Surat va maxrajni 4 ga bo‘lamiz: 1/2.',
      [
        mc(
          '2/3 × 3/4 ni toping.',
          ['1/2', '5/7', '6/7', '2/7'],
          '1/2',
          '6/12 ni qisqartirsak 1/2 bo‘ladi.',
        ),
        tf(
          'Kasrlarni ko‘paytirishda maxrajlar qo‘shiladi.',
          false,
          'Maxrajlar ham ko‘paytiriladi.',
        ),
        num('20 ning 3/5 qismi nechaga teng?', 12, '20 × 3 ÷ 5 = 12.'),
        txt('4/7 × 7/8 javobini a/b shaklida yozing.', '1/2', '7 lar qisqaradi: 4/8 = 1/2.'),
        txt('5/6 × 3/5 javobini qisqartirib yozing.', '1/2', '15/30 = 1/2.'),
        num('36 kg mahsulotning 5/6 qismi necha kilogramm?', 30, '36 ÷ 6 × 5 = 30 kg.'),
      ],
    ),
    lesson(
      'Kasrlarni bo‘lish',
      'Kasrlar bilan amallar',
      'Bo‘luvchining teskarisini ishlatib kasrlarni bo‘ling.',
      'Noldan farqli kasrga bo‘lish uning teskari kasriga ko‘paytirish bilan bir xil. a/b ÷ c/d = a/b × d/c; bu yerda b, c va d nol bo‘lmasligi kerak.\n\n1/2 ÷ 1/4 “yarim ichida nechta chorak bor?” degan savoldir. Yarim ikkita chorakdan iborat, shuning uchun javob 2. Formula bilan: 1/2 × 4/1 = 4/2 = 2.\n\nFaqat bo‘luvchi kasrning surat va maxrajini almashtiring. Birinchi kasr o‘zgarishsiz qoladi. Javobni tekshirish uchun topilgan bo‘linmani bo‘luvchiga ko‘paytiring: dastlabki bo‘linuvchi hosil bo‘lishi kerak.',
      '2/3 ÷ 4/5 = 2/3 × 5/4 = 10/12 = 5/6.\nTekshirish: 5/6 × 4/5 = 20/30 = 2/3.',
      [
        num('1/2 ÷ 1/4 nechaga teng?', 2, '1/2 × 4/1 = 2.'),
        tf(
          'Kasrga bo‘lish uchun bo‘luvchining teskarisiga ko‘paytiramiz.',
          true,
          'Bo‘luvchi noldan farqli bo‘lishi kerak.',
        ),
        mc(
          '2/3 ÷ 4/5 ni hisoblang.',
          ['5/6', '8/15', '3/10', '1/2'],
          '5/6',
          '2/3 × 5/4 = 10/12 = 5/6.',
        ),
        txt('3/7 ÷ 6/7 javobini qisqartirib yozing.', '1/2', '3/7 × 7/6 = 3/6 = 1/2.'),
        num('3/4 ÷ 1/8 nechaga teng?', 6, '3/4 × 8 = 6.'),
        num(
          '4,5 litr sharbatni 0,75 litrlik idishlarga quysak, nechta idish kerak?',
          6,
          '4,5 ÷ 0,75 = 6.',
          '4,5 va 0,75 ni 100 ga ko‘paytirib, 450 ÷ 75 ni hisoblang.',
        ),
      ],
    ),
    lesson(
      'Nisbat va proporsiya',
      'Nisbatlar',
      'Teng nisbat orqali noma’lum miqdorni toping.',
      'Nisbat ikki miqdorni taqqoslaydi. 2:3 nisbat “birinchi miqdorning 2 qismiga ikkinchisining 3 qismi mos keladi” degani. Jami 5 qism bor.\n\nTeng nisbatlardan tuzilgan tenglik proporsiya deyiladi. 2/3 = 4/6, chunki ikkala miqdor bir xil 2 ga ko‘paygan. Proporsiyada chetki hadlar ko‘paytmasi o‘rta hadlar ko‘paytmasiga teng.\n\nBir xil narxli mahsulotlar uchun son va umumiy narx to‘g‘ri proporsional. Avval bir dona narxini topib, keyin kerakli songa ko‘paytirish qulay. Masalada birliklar bir xil ekanini tekshiring.',
      '2:3 nisbatda bo‘lingan 25 qalam.\nJami qism: 2 + 3 = 5.\nBitta qism: 25 ÷ 5 = 5.\nBirinchi guruh: 2 × 5 = 10, ikkinchi guruh: 3 × 5 = 15.',
      [
        mc(
          '25 ni 2:3 nisbatda bo‘lsak, birinchi qism qancha?',
          ['5', '10', '15', '20'],
          '10',
          '25 ÷ 5 × 2 = 10.',
        ),
        tf('2:3 va 4:6 teng nisbatlar.', true, '2 va 3 ning ikkisini ham 2 ga ko‘paytirdik.'),
        num('15/5 = x/2 proporsiyada x ni toping.', 6, '15/5 = 3, demak x = 3 × 2 = 6.'),
        txt(
          'Ikki teng nisbatdan tuzilgan tenglik nima deyiladi?',
          'proporsiya',
          'Teng nisbatlar tengligi proporsiya deyiladi.',
        ),
        num(
          '5 ta daftar 15 000 so‘m. Shu narxda 8 ta daftar necha so‘m?',
          24000,
          'Bir daftar 3 000 so‘m. 8 × 3 000 = 24 000.',
        ),
        num(
          '3 kg olma 27 000 so‘m. Shu narxda 5 kg olma necha so‘m?',
          45000,
          '1 kg 9 000 so‘m. 5 kg 45 000 so‘m.',
        ),
      ],
    ),
    lesson(
      'Musbat va manfiy sonlar',
      'Butun sonlar',
      'Sonlar o‘qida manfiy sonlarni taqqoslang va hisoblang.',
      'Noldan o‘ngdagi sonlar musbat, chapdagi sonlar manfiy. Sonlar o‘qida o‘ngroqda turgan son kattaroq: −3 soni −8 dan katta. Sonning moduli nolgacha bo‘lgan masofa; shuning uchun |−6| = 6.\n\nTurli ishorali sonlarni qo‘shishda modullari ayiriladi va moduli kattaroq sonning ishorasi olinadi. −4 + 7 = 3. Manfiy sonni ayirish uning qarama-qarshisini qo‘shishdir: −6 − (−4) = −6 + 4 = −2.\n\nBir xil ishorali sonlar ko‘paytmasi musbat, turli ishorali sonlar ko‘paytmasi manfiy. Ifodada amallar tartibi saqlanadi. Natijani sonlar o‘qi yoki teskari amal bilan tekshiring.',
      '−3 × 4 + 5\nAvval ko‘paytiramiz: −3 × 4 = −12.\nKeyin qo‘shamiz: −12 + 5 = −7.',
      [
        num('−4 + 7 ni hisoblang.', 3, '7 − 4 = 3, katta modul musbat songa tegishli.'),
        tf('−8 soni −3 dan kichik.', true, '−8 sonlar o‘qida −3 dan chapda turadi.'),
        mc(
          '|−6| nechaga teng?',
          ['−6', '0', '6', '12'],
          '6',
          'Modul masofa bo‘lib, manfiy bo‘lmaydi.',
        ),
        txt(
          'Ikkita manfiy son ko‘paytmasining ishorasi qanday?',
          'musbat',
          'Bir xil ishoralar ko‘paytmasi musbat.',
        ),
        num('−6 − (−4) ni hisoblang.', -2, '−6 + 4 = −2.'),
        num('−3 × 4 + 5 ni hisoblang.', -7, '−12 + 5 = −7.'),
      ],
    ),
    lesson(
      'Foizli masalalar va chegirma',
      'Foizni qo‘llash',
      'Foiz miqdori bilan foizdan keyingi qiymatni farqlang.',
      'Foiz yuzdan bir ulush: p% = p/100. Sonning p foizi N × p/100 bilan topiladi. 80 ning 30% i 80 × 30/100 = 24.\n\nChegirma miqdori va yakuniy narx bir xil emas. 20 000 so‘mlik buyumga 15% chegirma 3 000 so‘m; xaridor 17 000 so‘m to‘laydi. Oshirishda esa topilgan miqdor dastlabki songa qo‘shiladi.\n\nFoiz qaysi boshlang‘ich miqdorga nisbatan olinayotganini aniqlang. 60 000 so‘mni 10% oshirish 66 000 so‘m beradi. Foiz va qiymat ma’lum bo‘lsa, boshlang‘ich sonni teskari hisob bilan topish mumkin.',
      '120 000 so‘mga 25% chegirma.\n25% = 1/4; chegirma 120 000 ÷ 4 = 30 000 so‘m.\nTo‘lov: 120 000 − 30 000 = 90 000 so‘m.',
      [
        mc(
          '20 000 so‘mga 15% chegirmadan keyingi narx?',
          ['3 000', '15 000', '17 000', '23 000'],
          '17 000',
          'Chegirma 3 000 so‘m; narx 17 000 so‘m.',
        ),
        tf('50 ning 20% i 10 ga teng.', true, '50 × 20/100 = 10.'),
        num('80 ning 30% i nechaga teng?', 24, '80 × 30/100 = 24.'),
        num(
          '60 000 so‘m 10% oshirilsa, yangi qiymat qancha?',
          66000,
          '10% = 6 000; yangi qiymat 66 000.',
        ),
        num(
          '120 000 so‘mga 25% chegirmadan keyingi narx qancha?',
          90000,
          '120 000 − 30 000 = 90 000.',
        ),
        num(
          'Bir sonning 25% i 18. Bu son nechaga teng?',
          72,
          '25% chorak, shuning uchun 18 × 4 = 72.',
        ),
      ],
    ),
    lesson(
      'Koordinata tekisligida nuqta',
      'Koordinatalar',
      'Nuqtaning x va y koordinatalarini tartib bilan o‘qing.',
      'Koordinata tekisligida gorizontal o‘q Ox, vertikal o‘q Oy deb ataladi. Ular (0, 0) nuqtada kesishadi. Nuqta (x, y) shaklida yoziladi: birinchi son gorizontal, ikkinchisi vertikal siljishni bildiradi.\n\n(3, 2) nuqtaga borish uchun boshlanishdan 3 birlik o‘ngga va 2 birlik yuqoriga yuramiz. x manfiy bo‘lsa chapga, y manfiy bo‘lsa pastga siljiymiz. O‘qlarda joylashgan nuqtalar choraklarga kirmaydi.\n\nIkkinchi chorakda x manfiy, y musbat: masalan (−2, 4). Bir xil x koordinatali nuqtalar vertikal chiziqda yotadi. Ularning vertikal masofasi y koordinatalar ayirmasining moduliga teng.',
      'A(2, 3), B(2, 8). Ikkala x bir xil, demak siljish faqat yuqoriga.\nMasofa |8 − 3| = 5 birlik.',
      [
        mc(
          '(3, 2) nuqtaning x koordinatasi?',
          ['2', '3', '5', '0'],
          '3',
          'Juftlikdagi birinchi son x koordinatasidir.',
        ),
        tf('(−2, 4) ikkinchi chorakda joylashgan.', true, 'x manfiy va y musbat.'),
        num('(0, 5) nuqtaning y koordinatasi qancha?', 5, 'Ikkinchi son y = 5.'),
        txt('Vertikal o‘q nomini yozing: Ox yoki Oy.', 'Oy|y', 'Vertikal o‘q Oy deyiladi.'),
        num('A(2, 3) va B(2, 8) orasidagi masofa necha birlik?', 5, 'Vertikal masofa |8 − 3| = 5.'),
        mc(
          '(−3, 1) nuqtadan 3 birlik o‘ngga yursak, qaysi nuqtaga kelamiz?',
          ['(0, 1)', '(−6, 1)', '(−3, 4)', '(3, 1)'],
          '(0, 1)',
          'x = −3 + 3 = 0, y esa 1 bo‘lib qoladi.',
        ),
      ],
    ),
  ],
  7: [
    lesson(
      'Algebraik ifodalar va o‘xshash hadlar',
      'Algebra tili',
      'O‘zgaruvchili ifodani hisoblang va o‘xshash hadlarni birlashtiring.',
      'Algebraik ifodada sonlar bilan birga o‘zgaruvchilar qatnashadi. 3x degani 3 × x. O‘zgaruvchiga qiymat berilganda ifodadagi barcha o‘rinlariga shu qiymat qo‘yiladi.\n\nBir xil o‘zgaruvchi va bir xil darajali hadlar o‘xshash hadlardir. 3x + 2x = 5x, chunki uchta x va ikkita x birgalikda beshta x bo‘ladi. Lekin 3x + 2y ni shu tarzda birlashtirib bo‘lmaydi.\n\nHadning oldidagi son koeffitsiyentdir. −4x ning koeffitsiyenti −4. Qavs ochishda ishoralarga e’tibor bering: 2(x + 3) = 2x + 6. Ifodani soddalashtirish bilan uning aniq sonli qiymatini topish turli vazifalar.',
      'x = 4 bo‘lganda 3x + 2 ning qiymati:\n3 × 4 + 2 = 12 + 2 = 14.\n3x + 2x − x ni esa qiymat qo‘ymasdan 4x deb soddalashtiramiz.',
      [
        num('x = 4 bo‘lsa, 3x + 2 nechaga teng?', 14, '3 × 4 + 2 = 14.'),
        tf('3x va 2y o‘xshash hadlardir.', false, 'O‘zgaruvchilari turlicha.'),
        mc(
          '3x + 2x ni soddalashtiring.',
          ['5x', '6x', '5x²', 'x'],
          '5x',
          'Koeffitsiyentlar 3 + 2 = 5.',
        ),
        num('−4x hadining koeffitsiyenti qancha?', -4, 'x ning oldidagi son −4.'),
        num('x = 5 bo‘lsa, 2(x + 3) − x nechaga teng?', 11, '2 × 8 − 5 = 11.'),
        txt(
          '3x + 2x − x ni bo‘sh joysiz yozib soddalashtiring.',
          '4x|4*x',
          '3 + 2 − 1 = 4, demak 4x.',
        ),
      ],
    ),
    lesson(
      'Bir noma’lumli chiziqli tenglama',
      'Tenglamalar',
      'Tenglikning ikkala tomonida bir xil amal bajarib yechim toping.',
      'Tenglama noma’lum qatnashgan tenglikdir. Tenglamani yechish — tenglikni rost qiladigan noma’lum qiymatini topish. Tenglikning ikkala tomoniga bir xil sonni qo‘shish yoki ayirish mumkin. Noldan farqli bir xil songa ko‘paytirish yoki bo‘lish ham tenglikni saqlaydi.\n\n2x + 5 = 17 da ikkala tomondan 5 ni ayiramiz: 2x = 12. Ikkala tomonni 2 ga bo‘lamiz: x = 6. Qavslar bo‘lsa avval qavsni ochish yoki mos amallar bilan sodda ko‘rinishga keltirish mumkin.\n\nYechimni tekshirish uchun uni dastlabki tenglamaga qo‘ying. Faqat o‘zgartirilgan ifodaga tekshirish yetarli emas: ishora xatosi avvalroq sodir bo‘lgan bo‘lishi mumkin.',
      '5x − 8 = 2x + 7\nIkkala tomondan 2x ni ayiramiz: 3x − 8 = 7.\n8 ni qo‘shamiz: 3x = 15.\n3 ga bo‘lamiz: x = 5. Tekshirish: 25 − 8 = 10 + 7 = 17.',
      [
        num('x + 7 = 19 tenglamada x ni toping.', 12, 'x = 19 − 7 = 12.'),
        tf('x/3 = 4 tenglamaning yechimi x = 12.', true, '12 ÷ 3 = 4.'),
        mc('2x + 5 = 17 tenglamaning yechimi?', ['6', '11', '8', '24'], '6', '2x = 12; x = 6.'),
        num('4x = 28 tenglamada x qancha?', 7, 'Ikkala tomonni 4 ga bo‘lamiz.'),
        num('5x − 8 = 2x + 7 tenglamada x ni toping.', 5, '3x = 15; x = 5.'),
        num('3(x − 2) = 21 tenglamada x ni toping.', 9, 'x − 2 = 7; x = 9.'),
      ],
    ),
    lesson(
      'Daraja va uning xossalari',
      'Darajalar',
      'Bir xil asosli darajalarni ko‘paytiring va ifodani hisoblang.',
      'a ning n-darajasi a sonining n marta ko‘paytirilishidir. 2³ = 2 × 2 × 2 = 8. a — asos, n — daraja ko‘rsatkichi. n musbat butun son bo‘lsa, bu ta’rif to‘g‘ridan-to‘g‘ri ishlaydi.\n\nBir xil asosli darajalar ko‘paytirilganda ko‘rsatkichlar qo‘shiladi: aᵐ × aⁿ = aᵐ⁺ⁿ. Masalan, 3² × 3³ = 3⁵. Asoslarni qo‘shish yoki ko‘paytirish bu qoidaning bir qismi emas.\n\nNoldan farqli asos uchun a⁰ = 1. Daraja amali ifodadagi ko‘paytirishdan oldin hisoblanadi. 5² − 3² = 25 − 9 = 16. Manfiy asos bilan ishlaganda qavslar muhim: (−2)² = 4.',
      '2³ × 2² = 2⁵ = 32.\nAlohida hisob bilan tekshiramiz: 8 × 4 = 32.',
      [
        num('2⁵ nechaga teng?', 32, '2 × 2 × 2 × 2 × 2 = 32.'),
        mc(
          '3² × 3³ qaysi darajaga teng?',
          ['3⁵', '3⁶', '9⁵', '6⁵'],
          '3⁵',
          'Bir xil asosda 2 + 3 = 5.',
        ),
        tf('a ≠ 0 bo‘lsa, a⁰ = 1.', true, 'Noldan farqli asosning nol darajasi 1.'),
        num('(−2)² nechaga teng?', 4, '(−2) × (−2) = 4.'),
        num('5² − 3² ni hisoblang.', 16, '25 − 9 = 16.'),
        num('2³ × 2² ni hisoblang.', 32, '8 × 4 = 32.'),
      ],
    ),
    lesson(
      'Qavs ochish va qisqa ko‘paytirish',
      'Ko‘phadlar',
      'Taqsimot qonuni va kvadrat formulalarini qo‘llang.',
      'Taqsimot qonuni a(b + c) = ab + ac ko‘rinishida yoziladi. Qavs tashqarisidagi son har bir hadga ko‘paytiriladi. 3(x + 2) = 3x + 6. Ayirishda ham har bir hadning ishorasi saqlanadi: 2(x − 4) = 2x − 8.\n\nYig‘indining kvadrati (a + b)² = a² + 2ab + b². O‘rtadagi 2ab hadini unutish keng tarqalgan xato. Ayirmaning kvadrati (a − b)² = a² − 2ab + b².\n\nFormulani ko‘paytirish orqali tekshirish mumkin: (a + b)(a + b) da a², ab, ba va b² hadlari hosil bo‘ladi. ab va ba yig‘indisi 2ab. O‘xshash hadlarni birlashtirganda darajalar bir xil bo‘lishi kerak.',
      '(x − 4)² = x² − 2 × x × 4 + 4² = x² − 8x + 16.\nx = 6 bilan tekshiring: chap tomon 2² = 4; o‘ng tomon 36 − 48 + 16 = 4.',
      [
        mc(
          '3(x + 2) ning ochilgan ko‘rinishi?',
          ['3x + 6', '3x + 2', 'x + 6', '6x'],
          '3x + 6',
          '3 ikkala hadga ko‘paytiriladi.',
        ),
        tf('a(b + c) = ab + ac.', true, 'Bu taqsimot qonuni.'),
        num('x = 2 bo‘lsa, 2(x + 3) nechaga teng?', 10, '2 × (2 + 3) = 10.'),
        num('2x² + 3x² dagi x² ning yakuniy koeffitsiyenti?', 5, '2 + 3 = 5.'),
        num('(7 + 3)² ni hisoblang.', 100, '10² = 100; formula bilan ham 49 + 42 + 9 = 100.'),
        mc(
          '(x − 4)² ni oching.',
          ['x² − 8x + 16', 'x² + 16', 'x² − 4x + 16', 'x² − 16'],
          'x² − 8x + 16',
          'a² − 2ab + b² formulasi ishlatiladi.',
        ),
      ],
    ),
    lesson(
      'Chiziqli funksiya va qiymatlar jadvali',
      'Funksiyalar',
      'y = kx + b da x ga mos y ni toping.',
      'Funksiya x qiymatiga ma’lum qoida bilan y qiymatini mos qo‘yadi. Chiziqli funksiya y = kx + b shaklida yoziladi. k va b o‘zgarmas sonlar, x esa o‘zgaruvchi. Uning grafigi to‘g‘ri chiziqdir.\n\ny = 2x + 1 uchun x = 0 bo‘lsa y = 1, x = 1 bo‘lsa y = 3, x = 2 bo‘lsa y = 5. Bu qiymatlarni jadvalga yozib, (x, y) nuqtalarni koordinata tekisligida belgilaymiz.\n\nb grafikning Oy o‘qi bilan kesishishidagi y koordinatasini bildiradi. Agar b nol bo‘lmasa, chiziq koordinatalar boshidan o‘tmaydi. k musbat bo‘lsa, x oshishi bilan y ham oshadi. Noma’lum x ni topishda formulani tenglama sifatida yechish mumkin.',
      'y = 3x − 2 va y = 10 bo‘lsin.\n10 = 3x − 2 → 12 = 3x → x = 4.\nTekshirish: 3 × 4 − 2 = 10.',
      [
        num('y = 2x + 1 da x = 3. y qancha?', 7, '2 × 3 + 1 = 7.'),
        tf(
          'y = 2x + 1 grafigi (0, 0) dan o‘tadi.',
          false,
          'x = 0 bo‘lsa y = 1; (0, 1) dan o‘tadi.',
        ),
        mc(
          'Chiziqli funksiyaning grafigi qanday?',
          ['To‘g‘ri chiziq', 'Aylana', 'Uchburchak', 'Faqat bitta nuqta'],
          'To‘g‘ri chiziq',
          'y = kx + b to‘g‘ri chiziqni tasvirlaydi.',
        ),
        num('y = 2x + 1 da x = 0. y qancha?', 1, '2 × 0 + 1 = 1.'),
        num('y = −3x + 4 da x = 2. y qancha?', -2, '−6 + 4 = −2.'),
        num('y = 3x − 2 da y = 10. x ni toping.', 4, '3x = 12; x = 4.'),
      ],
    ),
    lesson(
      'Uchburchak burchaklari va tomonlari',
      'Geometriya',
      'Ichki burchaklar yig‘indisi va uchburchak tengsizligidan foydalaning.',
      'Uchburchakning uchta ichki burchagi yig‘indisi 180°. Ikkita burchak ma’lum bo‘lsa, uchinchisi 180° dan ularning yig‘indisini ayirish orqali topiladi. To‘g‘ri burchakli uchburchakning bitta burchagi 90°.\n\nTeng yonli uchburchakda teng tomonlar qarshisidagi burchaklar teng. Uchala tomoni teng uchburchak teng tomonli deyiladi; undagi har bir burchak 60°.\n\nUchburchak hosil bo‘lishi uchun har qanday ikki tomon yig‘indisi uchinchi tomondan katta bo‘lishi kerak. 2, 3 va 6 uzunliklar uchburchak hosil qilmaydi, chunki 2 + 3 = 5 va bu 6 dan kichik. Tashqi burchak unga qo‘shni bo‘lmagan ikkita ichki burchak yig‘indisiga teng.',
      'Teng yonli uchburchakning uchidagi burchak 40°.\nQolgan ikki burchak yig‘indisi 180 − 40 = 140°.\nUlar teng: 140 ÷ 2 = 70°.',
      [
        num('Ikki burchak 60° va 50°. Uchinchi burchak necha gradus?', 70, '180 − 60 − 50 = 70°.'),
        tf(
          'Tashqi burchak unga qo‘shni bo‘lmagan ikki ichki burchak yig‘indisiga teng.',
          true,
          'Bu ichki burchaklar yig‘indisi 180° ekanidan kelib chiqadi.',
        ),
        mc(
          'To‘g‘ri burchakning o‘lchami?',
          ['45°', '60°', '90°', '180°'],
          '90°',
          'To‘g‘ri burchak 90°.',
        ),
        txt(
          'Uchala tomoni teng uchburchak qanday ataladi?',
          'teng tomonli|teng tomonli uchburchak',
          'Uchala tomoni teng bo‘lsa, teng tomonli deyiladi.',
        ),
        num(
          'Teng yonli uchburchak uchidagi burchak 40°. Har bir asos burchagi necha gradus?',
          70,
          '(180 − 40) ÷ 2 = 70°.',
        ),
        mc(
          'Qaysi tomonlar uchburchak hosil qila olmaydi?',
          ['2, 3, 6', '3, 4, 5', '4, 4, 6', '5, 5, 5'],
          '2, 3, 6',
          '2 + 3 = 5 < 6, uchburchak tengsizligi bajarilmaydi.',
        ),
      ],
    ),
  ],
};
